### ISSUE TITLE
Nextjs example

### ISSUE THREAD

**Issue by fimbault** [meilisearch/MeiliSearch#1046]
**Is your feature request related to a problem? Please describe.**
Quick starter

**Describe the solution you'd like**
Adapted from the [react example](https://docs.meilisearch.com/instant-search-react-app/#how-to-implement-instant-search-within-5-minutes-in-your-react-app)

**Current issue**
From a quick test, calls with nodejs seem to be an issue 

Example stack trace (here with getServerSideProps)
Error [MeiliSearchCommunicationError]: Not Found
    at httpErrorHandler (/Code/test/test-meilisearch/node_modules/meilisearch/dist/bundles/meilisearch.umd.js:245:15)
    at HttpRequests.<anonymous> (/Code/test/test-meilisearch/node_modules/meilisearch/dist/bundles/meilisearch.umd.js:325:17)
    at step (/Code/test/test-meilisearch/node_modules/meilisearch/dist/bundles/meilisearch.umd.js:79:27)
    at Object.throw (/Code/test/test-meilisearch/node_modules/meilisearch/dist/bundles/meilisearch.umd.js:60:57)
    at rejected (/Code/test/test-meilisearch/node_modules/meilisearch/dist/bundles/meilisearch.umd.js:51:69)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  type: 'MeiliSearchCommunicationError',
  errno: undefined,
  code: undefined
}

**Comment by fimbault** [comment]
Actually it seems to work, it's just that to go quickly I used the default meilisearch that come with the example, but a more recent library version. So it seems due to MeiliSearch versions are being not compatible with each other, which is normal.

**Comment by curquiza** [comment]
Hello @fimbault!

Yes, you're right there are incompatible versions, this article in our docs indeed not up-to-date, sorry about that.
We are currently working on adding more front-end articles that would better fit with the new versions of MeiliSearch. I hope they would make your MeiliSearch experience easier!

Sorry for this inconvenient, and thanks for using MeiliSearch 😁

**Comment by fimbault** [comment]
no problem, here's the small test in case it helps someone https://github.com/fimbault/test-meilisearch-nextjs
