### ISSUE TITLE
Server under high pressure (e.g. indexing) could throw 408 errors

### ISSUE THREAD

**Issue by raszi** [meilisearch/MeiliSearch#1202]
**Describe the bug**

When a server is indexing then it could start throwing 408 errors on regular search requests, probably because of actix/actix-web#1269

**To Reproduce**
1. Start a bigger indexing
2. Issue multiple requests to the instance which is doing the indexing
3. Start to see 408 errors

```
$ curl -v http://127.0.0.1:7700
* Expire in 0 ms for 6 (transfer 0x55f15b213ec0)
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x55f15b213ec0)
* Connected to 127.0.0.1 (127.0.0.1) port 7700 (#0)
> GET / HTTP/1.1
> Host: 127.0.0.1:7700
> User-Agent: curl/7.64.0
> Accept: */*
> 

< HTTP/1.1 408 Request Timeout
< content-length: 0
< connection: close
< date: Thu, 21 Jan 2021 09:24:39 GMT
< 
* Closing connection 0
```

**Expected behavior**

The instance would serve the requests without issues (or with a longer response time) or throw a `503` error.

**Comment by MarinPostma** [comment]
uhm could be linked to #1178, needs to be investigated. Thanks for the report!

**Comment by curquiza** [comment]
Hello @raszi, and everyone following the issue!

The [first RC of MeiliSearch v0.21.0](https://github.com/meilisearch/MeiliSearch/releases/tag/v0.21.0rc0) is out.
We did our best to fix indexation and crash issues. We succeeded to improve it, but not to totally fix them.

You can test this new release by downloading the binaries available in this release.
Or you can use it with docker:

```bash
docker run -p 7700:7700 getmeili/meilisearch:v0.21.0rc0 ./meilisearch
```

We will still improve this after the release of the v0.21.0. We would rather release a non-completely optimized version rather than delay it and, at the same time, delay the release of new features. Be sure we are doing our best to always improve these indexation issues.

As a reminder:
* despite the improvements, we always recommend pushing your documents to MeiliSearch by batch and not one by one. The maximum payload size of MeiliSearch is 100Mb and [can be optionally increased](https://docs.meilisearch.com/reference/features/configuration.html#payload-limit-size). It means most of the dataset can be pushed with one call to the API.
* If you still have a memory crash, it means the RAM of your machine might not be adapted to your dataset size. We recommend increasing the RAM of your machine.

Thanks for your patience and your help with this! ❤️

**Comment by curquiza** [comment]
Hello everyone reading this issue.

I close this issue due to the lack of feedback since it was happening with an old version of Meilisearch. We need more info to fix this kind of bug.

However, for anyone having issues in general with indexation performance, like this issue, please, refer to [this discussion](https://github.com/meilisearch/meilisearch/discussions/2131). Your feedback will be really appreciated 🙂

**Comment by raszi** [comment]
I don't think that this issue should be closed.

Nobody requested any testing from me and in your reply you explicitly stated that it wasn't a complete fix.

**Comment by raszi** [comment]
Sorry to say, but I cannot see any request there.

I didn't do any testing on my side since the fix wasn't full and we changed the way our indices being deployed.

**Comment by raszi** [comment]
As I described in the bug, to reproduce it you need to start indexing then do a benchmark on the instance doing the indexing, then you'll see the 408 errors.

Have you tried that?

**Comment by curquiza** [comment]
> Have you tried that?

Yes, of course, we tried! 🙂
We did not succeed to reproduce the issue, even once. And we did not get any other report like this in 1 year.

> Sorry to say, but I cannot see any request there.

Sorry for the confusion, but when I let the message say v0.21.0 was released, it was to check if the issue was still present with the new version. Indeed we did some deep changes in the engine, so this issue is maybe not present. Since we cannot reproduce it, we need feedback to confirm or not.

**Comment by bumzack** [comment]
Hi, 

first thanks for making meilisearch and making it available on github.

I am seeing the same problem as mentioned in the original issue. I am comparing and learning meilisearch and solr using the following dataset: https://datasets.imdbws.com/

I've tried to put together a minimal reproducible example: https://github.com/bumzack/meili_reproducible_408
It is not very minimalistic, but I could not find an easier way. Using this repo, a 408 response can be reproduced under high load reading documents and inserting documents in parallel.

Basically what I am trying to do is the following: I have 3 indexes. I read paginated data from one of the indexes, query the other 2 indexes and combine the data into a new document and insert the new documents in an index. This is done in parallel using tokio threads.

```
[2023-04-08T18:51:50Z WARN  meilisearch_sdk::request] Expected response code 200, got 408
[2023-04-08T18:51:50Z INFO  create_combined_index] found 100 movies
[2023-04-08T18:51:50Z INFO  create_combined_index] error reading persons Error parsing response JSON: invalid type: null, expected struct MeilisearchError at line 1 column 4
thread 'tokio-runtime-worker' panicked at 'should not happen. error reading persons.', create_combined_index/src/main.rs:142:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[2023-04-08T18:51:50Z WARN  meilisearch_sdk::request] Expected response code 200, got 408
[2023-04-08T18:51:50Z INFO  create_combined_index] error reading persons Error parsing response JSON: invalid type: null, expected struct MeilisearchError at line 1 column 4
thread 'tokio-runtime-worker' panicked at 'should not happen. error reading persons.', create_combined_index/src/main.rs:142:13
[2023-04-08T18:51:50Z WARN  meilisearch_sdk::request] Expected response code 200, got 408
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: ParseError(Error("invalid type: null, expected struct MeilisearchError", line: 1, column: 4))', create_combined_index/src/main.rs:118:10
```


I am using `meilisearch 1.1.0` and the meilisearch rust client v.0.23.0.
rust version: `rustc 1.68.2`

I could not reproduce 408 response with a smaller dataset.

Please see the repo for more details.

If you need more details I'll try and provide all the relevant information.
