### ISSUE TITLE
Bug in snapshot test

### ISSUE THREAD

**Issue by MarinPostma** [meilisearch/MeiliSearch#1434]
The CI for meilisearch/transplant#113 will not pass because the integration test `perform_snapshot` refuses to pass on the CI VMs. The tests seems to pass with `bors try` fut not with `bors merge`. I have tested il locally extensively, on multiple distributions (arch, nixos, and ubuntu), and I haven't been able to reproduce. @curquiza has tested the feature on Macos and had no issue.

It has been decided that this test will be ignored, until we find a solution.

**Comment by scampi** [comment]
I have not been able to find the error, logs got deleted as it is too old. I got the following error on my local. Is it the error you encountered ?

- `rustc 1.55.0-beta.8 (2296b1665 2021-08-27)`
- 23ccf4429ebbaf250c5eb875d6365b7f6a85a6f9

```
---- snapshot::perform_snapshot stdout ----
thread 'snapshot::perform_snapshot' panicked at 'called `Result::unwrap()` on an `Err` value: snapshot doesn't exist at "/home/yfful/documents/code/MeiliSearch/meilisearch-http/./.tmpU6t4En/db.snapshot"', meilisearch-http/tests/common/server.rs:37:35
stack backtrace:
   0: rust_begin_unwind
             at /rustc/2296b16654165ebe0849a8bba67ea46e3c6f0c7c/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/2296b16654165ebe0849a8bba67ea46e3c6f0c7c/library/core/src/panicking.rs:92:14
   2: core::result::unwrap_failed
             at /rustc/2296b16654165ebe0849a8bba67ea46e3c6f0c7c/library/core/src/result.rs:1599:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/2296b16654165ebe0849a8bba67ea46e3c6f0c7c/library/core/src/result.rs:1281:23
   4: integration::common::server::Server::new_with_options::{{closure}}
             at ./tests/common/server.rs:37:20
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/2296b16654165ebe0849a8bba67ea46e3c6f0c7c/library/core/src/future/mod.rs:80:19
   6: integration::snapshot::perform_snapshot::{{closure}}
             at ./tests/snapshot/mod.rs:44:18
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/2296b16654165ebe0849a8bba67ea46e3c6f0c7c/library/core/src/future/mod.rs:80:19
   8: <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll::{{closure}}::{{closure}}
             at /home/yfful/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/task/local.rs:634:65
   9: tokio::coop::with_budget::{{closure}}
             at /home/yfful/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/coop.rs:106:9
  10: std::thread::local::LocalKey<T>::try_with
             at /rustc/2296b16654165ebe0849a8bba67ea46e3c6f0c7c/library/std/src/thread/local.rs:399:16
  11: std::thread::local::LocalKey<T>::with
             at /rustc/2296b16654165ebe0849a8bba67ea46e3c6f0c7c/library/std/src/thread/local.rs:375:9
  12: tokio::coop::with_budget
             at /home/yfful/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/coop.rs:99:5
  13: tokio::coop::budget
             at /home/yfful/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/coop.rs:76:5
  14: <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll::{{closure}}
             at /home/yfful/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/task/local.rs:634:42
  15: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /home/yfful/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/macros/scoped_tls.rs:61:9
  16: tokio::task::local::LocalSet::with
             at /home/yfful/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/task/local.rs:548:9
  17: <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll
             at /home/yfful/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/task/local.rs:624:9
  18: tokio::task::local::LocalSet::run_until::{{closure}}
             at /home/yfful/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/task/local.rs:498:9
  19: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/2296b16654165ebe0849a8bba67ea46e3c6f0c7c/library/core/src/future/mod.rs:80:19
  20: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/2296b16654165ebe0849a8bba67ea46e3c6f0c7c/library/core/src/future/future.rs:119:9
  21: tokio::runtime::basic_scheduler::Inner<P>::block_on::{{closure}}::{{closure}}
             at /home/yfful/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/runtime/basic_scheduler.rs:213:62
  22: tokio::coop::with_budget::{{closure}}
             at /home/yfful/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/coop.rs:106:9
  23: std::thread::local::LocalKey<T>::try_with
             at /rustc/2296b16654165ebe0849a8bba67ea46e3c6f0c7c/library/std/src/thread/local.rs:399:16
  24: std::thread::local::LocalKey<T>::with
             at /rustc/2296b16654165ebe0849a8bba67ea46e3c6f0c7c/library/std/src/thread/local.rs:375:9
  25: tokio::coop::with_budget
             at /home/yfful/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/coop.rs:99:5
  26: tokio::coop::budget
             at /home/yfful/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/coop.rs:76:5
  27: tokio::runtime::basic_scheduler::Inner<P>::block_on::{{closure}}
             at /home/yfful/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/runtime/basic_scheduler.rs:213:39
  28: tokio::runtime::basic_scheduler::enter::{{closure}}
             at /home/yfful/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/runtime/basic_scheduler.rs:323:29
  29: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /home/yfful/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/macros/scoped_tls.rs:61:9
  30: tokio::runtime::basic_scheduler::enter
             at /home/yfful/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/runtime/basic_scheduler.rs:323:5
  31: tokio::runtime::basic_scheduler::Inner<P>::block_on
             at /home/yfful/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/runtime/basic_scheduler.rs:202:9
  32: tokio::runtime::basic_scheduler::InnerGuard<P>::block_on
             at /home/yfful/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/runtime/basic_scheduler.rs:516:9
  33: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on
             at /home/yfful/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/runtime/basic_scheduler.rs:162:24
  34: tokio::runtime::Runtime::block_on
             at /home/yfful/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/runtime/mod.rs:450:46
  35: tokio::task::local::LocalSet::block_on
             at /home/yfful/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/task/local.rs:459:9
  36: actix_rt::runtime::Runtime::block_on
             at /home/yfful/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-rt-2.2.0/src/runtime.rs:85:9
  37: actix_rt::system::SystemRunner::block_on
             at /home/yfful/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-rt-2.2.0/src/system.rs:186:9
  38: integration::snapshot::perform_snapshot
             at ./tests/snapshot/mod.rs:10:1
  39: integration::snapshot::perform_snapshot::{{closure}}
             at ./tests/snapshot/mod.rs:10:1
  40: core::ops::function::FnOnce::call_once
             at /rustc/2296b16654165ebe0849a8bba67ea46e3c6f0c7c/library/core/src/ops/function.rs:227:5
  41: core::ops::function::FnOnce::call_once
             at /rustc/2296b16654165ebe0849a8bba67ea46e3c6f0c7c/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by MarinPostma** [comment]
Yes this one I know of, but I suspect it is coming from the test itself, and not the snapshot. You can take a look at it if you're interested, but I judge this non critical.

**Comment by MarinPostma** [comment]
I have not seen this occuring again, i am closing this. If we see it happening again, we'll reopen.
