### ISSUE TITLE
Panicking in grenad when indexing

### ISSUE THREAD

**Issue by bb** [meilisearch/MeiliSearch#1590]
**Describe the bug**
When indexing a certain dataset, I get reproducible panicks in Grenad sorter.rs. 

**MeiliSearch version:** This happens in rc4, as well as in the branches fix-facets-distribution (f3e595e2) and test-new-indexer (10ac08bc). It does *not* happen in 0.20.0.

### Stacktrace from test-new-indexer

```
thread 'tokio-runtime-worker' panicked at 'range end index 3776 out of range for slice of length 1024', /Users/bb/.cargo/registry/src/github.com-1ecc6299db9ec823/grenad-0.2.0/src/sorter.rs:261:9
stack backtrace:
   0:        0x1067b27ae - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h7dac4b58aa11870a
   1:        0x1067ecc5e - core::fmt::write::h53badd02f711efbe
   2:        0x1067adeea - std::io::Write::write_fmt::hd02c4bbaf6463567
   3:        0x1067cb25f - std::panicking::default_hook::{{closure}}::ha7d22468d4529f02
   4:        0x1067cadea - std::panicking::default_hook::hc6c5fb91e7ed228a
   5:        0x1067cb7d0 - std::panicking::rust_panic_with_hook::h94fd567d38cd4da7
   6:        0x1067b2b25 - std::panicking::begin_panic_handler::{{closure}}::h953a8f32e4882703
   7:        0x1067b2928 - std::sys_common::backtrace::__rust_end_short_backtrace::h8472811b9ff0c597
   8:        0x1067cb363 - _rust_begin_unwind
   9:        0x1068313ff - core::panicking::panic_fmt::h5a271c2839c7a480
  10:        0x106831536 - core::slice::index::slice_end_index_len_fail::h67c2b8168bc61e9b
  11:        0x10638a242 - <core::ops::range::Range<usize> as core::slice::index::SliceIndex<[T]>>::index_mut::h3842e9d9b6666724
                               at /private/tmp/rust-20210619-72017-18okvud/rustc-1.53.0-src/library/core/src/slice/index.rs:251:13
  12:        0x10638a242 - <core::ops::range::RangeTo<usize> as core::slice::index::SliceIndex<[T]>>::index_mut::heb51a85137a651b0
                               at /private/tmp/rust-20210619-72017-18okvud/rustc-1.53.0-src/library/core/src/slice/index.rs:291:9
  13:        0x10638a242 - core::slice::index::<impl core::ops::index::IndexMut<I> for [T]>::index_mut::h266214369d154748
                               at /private/tmp/rust-20210619-72017-18okvud/rustc-1.53.0-src/library/core/src/slice/index.rs:26:9
  14:        0x10638a242 - grenad::sorter::Entries::reallocate_buffer::h21dd8ac23bce03ed
                               at /Users/bb/.cargo/registry/src/github.com-1ecc6299db9ec823/grenad-0.2.0/src/sorter.rs:261:9
  15:        0x10638a242 - grenad::sorter::Entries::insert::hd515713c47f81a55
                               at /Users/bb/.cargo/registry/src/github.com-1ecc6299db9ec823/grenad-0.2.0/src/sorter.rs:185:13
  16:        0x106318110 - grenad::sorter::Sorter<MF>::insert::hcd0b51235b0c3d9b
                               at /Users/bb/.cargo/registry/src/github.com-1ecc6299db9ec823/grenad-0.2.0/src/sorter.rs:312:13
  17:        0x10635efa8 - milli::update::words_level_positions::WordsLevelPositions::execute::h023ba6a2ca164511
                               at /Users/bb/.cargo/git/checkouts/milli-00376cd5db949a15/a1dc915/milli/src/update/words_level_positions.rs:123:21
  18:        0x105f9b983 - milli::update::index_documents::IndexDocuments::execute_prefix_databases::h7e5ba87a9368b197
                               at /Users/bb/.cargo/git/checkouts/milli-00376cd5db949a15/a1dc915/milli/src/update/index_documents/mod.rs:353:9
  19:        0x105f9b983 - milli::update::index_documents::IndexDocuments::execute_raw::hff6f8a4eb164e9ca
                               at /Users/bb/.cargo/git/checkouts/milli-00376cd5db949a15/a1dc915/milli/src/update/index_documents/mod.rs:290:9
  20:        0x105f9b983 - milli::update::index_documents::IndexDocuments::execute::h30a9e6d720853a2d
                               at /Users/bb/.cargo/git/checkouts/milli-00376cd5db949a15/a1dc915/milli/src/update/index_documents/mod.rs:183:9
  21:        0x106042915 - meilisearch_http::index::updates::<impl meilisearch_http::index::Index>::update_documents_txn::h99cf23fdf4d64d8a
                               at /Users/bb/src/meilisearch/MeiliSearch/meilisearch-http/src/index/updates.rs:225:30
  22:        0x106042915 - meilisearch_http::index::updates::<impl meilisearch_http::index::Index>::update_documents::ha636a071f30ae821
                               at /Users/bb/src/meilisearch/MeiliSearch/meilisearch-http/src/index/updates.rs:183:22
  23:        0x10600950f - meilisearch_http::index::update_handler::UpdateHandler::handle_update::h534a06902961abc3
                               at /Users/bb/src/meilisearch/MeiliSearch/meilisearch-http/src/index/update_handler.rs:75:18
  24:        0x105f42d20 - meilisearch_http::index_controller::index_actor::actor::IndexActor<S>::handle_update::{{closure}}::{{closure}}::h89ffbc5b99910c93
                               at /Users/bb/src/meilisearch/MeiliSearch/meilisearch-http/src/index_controller/index_actor/actor.rs:174:35
  25:        0x105f42d20 - <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll::h6974e82f3235dcb4
                               at /Users/bb/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/runtime/blocking/task.rs:42:21
  26:        0x105f800bb - tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}::h054ba5c5b865df0e
                               at /Users/bb/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/runtime/task/core.rs:243:17
  27:        0x105f800bb - tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::ha42a6fc2fbc4da92
                               at /Users/bb/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/loom/std/unsafe_cell.rs:14:9
  28:        0x105f800bb - tokio::runtime::task::core::CoreStage<T>::poll::hdf4058b250efe0b2
                               at /Users/bb/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/runtime/task/core.rs:233:13
  29:        0x1060e6fd5 - tokio::runtime::task::harness::poll_future::{{closure}}::h683977c493d73f6d
                               at /Users/bb/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/runtime/task/harness.rs:427:23
  30:        0x1060e6fd5 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hf29933c7ead25963
                               at /private/tmp/rust-20210619-72017-18okvud/rustc-1.53.0-src/library/std/src/panic.rs:344:9
  31:        0x1060e6fd5 - std::panicking::try::do_call::h73fe24ce701b0ac3
                               at /private/tmp/rust-20210619-72017-18okvud/rustc-1.53.0-src/library/std/src/panicking.rs:379:40
  32:        0x1060e6fd5 - std::panicking::try::h912db6015a200185
                               at /private/tmp/rust-20210619-72017-18okvud/rustc-1.53.0-src/library/std/src/panicking.rs:343:19
  33:        0x1060e6fd5 - std::panic::catch_unwind::h122effb340ec7df7
                               at /private/tmp/rust-20210619-72017-18okvud/rustc-1.53.0-src/library/std/src/panic.rs:431:14
  34:        0x1060e6fd5 - tokio::runtime::task::harness::poll_future::h5033d58fc56eda29
                               at /Users/bb/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/runtime/task/harness.rs:414:19
  35:        0x1060e6fd5 - tokio::runtime::task::harness::Harness<T,S>::poll_inner::he70f9264c52423d4
                               at /Users/bb/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/runtime/task/harness.rs:89:9
  36:        0x1060e6fd5 - tokio::runtime::task::harness::Harness<T,S>::poll::hdecde7460f47f371
                               at /Users/bb/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/runtime/task/harness.rs:59:15
  37:        0x10677e551 - tokio::runtime::task::raw::RawTask::poll::h416361a9ad091bc1
                               at /Users/bb/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/runtime/task/raw.rs:66:18
  38:        0x10677e551 - tokio::runtime::task::Notified<S>::run::h3dba549bad50f391
                               at /Users/bb/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/runtime/task/mod.rs:171:9
  39:        0x10677e551 - tokio::runtime::blocking::pool::Inner::run::h93e9ae0a371f12a8
                               at /Users/bb/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/runtime/blocking/pool.rs:265:17
  40:        0x10677e551 - tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}::h58a23ff18807af16
                               at /Users/bb/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/runtime/blocking/pool.rs:245:17
  41:        0x10677e551 - std::sys_common::backtrace::__rust_begin_short_backtrace::h4d450a4824b51278
                               at /private/tmp/rust-20210619-72017-18okvud/rustc-1.53.0-src/library/std/src/sys_common/backtrace.rs:125:18
  42:        0x106775dd1 - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::hfb5b3b2109757c4c
                               at /private/tmp/rust-20210619-72017-18okvud/rustc-1.53.0-src/library/std/src/thread/mod.rs:481:17
  43:        0x106775dd1 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hefce693b736faac6
                               at /private/tmp/rust-20210619-72017-18okvud/rustc-1.53.0-src/library/std/src/panic.rs:344:9
  44:        0x106775dd1 - std::panicking::try::do_call::hb8c2a5980ff5ade3
                               at /private/tmp/rust-20210619-72017-18okvud/rustc-1.53.0-src/library/std/src/panicking.rs:379:40
  45:        0x106775dd1 - std::panicking::try::h6b0a5c1f8dba737d
                               at /private/tmp/rust-20210619-72017-18okvud/rustc-1.53.0-src/library/std/src/panicking.rs:343:19
  46:        0x106775dd1 - std::panic::catch_unwind::h12b05d921df6ec85
                               at /private/tmp/rust-20210619-72017-18okvud/rustc-1.53.0-src/library/std/src/panic.rs:431:14
  47:        0x106775dd1 - std::thread::Builder::spawn_unchecked::{{closure}}::h51042bbb1f92c44e
                               at /private/tmp/rust-20210619-72017-18okvud/rustc-1.53.0-src/library/std/src/thread/mod.rs:480:30
  48:        0x106775dd1 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h2d661b4704f565fa
                               at /private/tmp/rust-20210619-72017-18okvud/rustc-1.53.0-src/library/core/src/ops/function.rs:227:5
  49:        0x1067aee1b - std::sys::unix::thread::Thread::new::thread_start::h26c063646f1d014f
  50:     0x7fff204a28fc - __pthread_start
```

**To Reproduce**

Unfortunately, I cannot share the dataset publicly, but this is what I do in a Rails project with latest meilisearch-rails:

`Post.ms_clear_index! rescue puts("post index was not there yet"); Post.where("(id >= 788000 and id <= 788984) or id >= 789050").ms_reindex!(1000000, true); Post.ms_index.get_all_update_status.last`

From the initial issue with the full dataset of about 792000 posts, I managed to boil it down to just 3268.

_Edit: shared dataset privately with @curquiza._

**Expected behavior**
No panick. Success of indexing or at least a more helpful error message.

**Additional context**

Tested on MacOS and RC4 additionally in official Docker image.
There was some discussion in Slack about it: https://meilicommunity.slack.com/archives/CP9DVS1RQ/p1629115852130100?thread_ts=1626768225.066500&cid=CP9DVS1RQ (scroll up and down...)

**Comment by curquiza** [comment]
Thanks a lot for this report @bb!
If someone has the same issue and can share the dataset, it would be awesome 🙏

**Comment by bb** [comment]
Thanks a lot @curquiza. @Kerollmops released a new version of https://github.com/Kerollmops/grenad (0.3.0) but the PR https://github.com/meilisearch/MeiliSearch/pull/1588 still references 0.2.0: https://github.com/meilisearch/milli/pull/308/files#r689681516.

Currently it does not build for me.

**Comment by curquiza** [comment]
Yes! Some changes has to be done on the branch! Kero is doing them 😊

**Comment by curquiza** [comment]
The branch is up to date now, you can test it now :)

**Comment by bb** [comment]
It wasn't compiling with Rust 1.53 on MacOS (sysinfo-0.20.0 had 31 errors, even after cargo clean) but after upgrading to 1.54 it worked fine and I verified the minimal test case via curl, the minimal test case via meilisearch-rails and a slightly bigger testcase via meilisearch-rails.

The good news is, the minimal test case worked. The bad news is, the slightly bigger test case panicked:

```
thread 'tokio-runtime-worker' panicked at '[117, 110, 116, 101, 114, 2, 115, 116, 117, 116, 122, 117, 110, 103, 0, 0, 0, 20, 95, 0, 0, 20, 95] must be greater than [117, 110, 116, 101, 114, 3, 0, 0, 24, 0, 0, 0, 24, 63]', /Users/bb/.cargo/registry/src/github.com-1ecc6299db9ec823/grenad-0.3.0/src/block_builder.rs:35:17
stack backtrace:
   0:        0x109cb8e5e - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h56d3732f7259ab13
   1:        0x109cf329c - core::fmt::write::h9969b11baa131b36
   2:        0x109cb5a8a - std::io::Write::write_fmt::hac493b5dc1c797ed
   3:        0x109cb6b0f - std::panicking::default_hook::{{closure}}::h17b2a28591715ec6
   4:        0x109cb671e - std::panicking::default_hook::h05729510b1584e59
   5:        0x109cb71c3 - std::panicking::rust_panic_with_hook::hb50a805db2efdc99
   6:        0x109cb96c5 - std::panicking::begin_panic_handler::{{closure}}::h4c2342b1ce628d41
   7:        0x109cb8fa8 - std::sys_common::backtrace::__rust_end_short_backtrace::h0567447a118aeab8
   8:        0x109cb6c13 - _rust_begin_unwind
   9:        0x109d35a3b - std::panicking::begin_panic_fmt::h03b2101261b11fc4
  10:        0x109893ff0 - grenad::block_builder::BlockBuilder::insert::hc4976c610b8290eb
                               at /Users/bb/.cargo/registry/src/github.com-1ecc6299db9ec823/grenad-0.3.0/src/block_builder.rs:35:17
  11:        0x10985390b - grenad::writer::Writer<W>::insert::hc518e0be1d0f0ba2
                               at /Users/bb/.cargo/registry/src/github.com-1ecc6299db9ec823/grenad-0.3.0/src/writer.rs:111:12
  12:        0x109878f6e - milli::update::words_level_positions::write_level_entry::h08c9e02e91f483f0
                               at /Users/bb/.cargo/git/checkouts/milli-00376cd5db949a15/03aa120/milli/src/update/words_level_positions.rs:265:5
  13:        0x109877c0c - milli::update::words_level_positions::compute_positions_levels::h03b71a5cd3971063
                               at /Users/bb/.cargo/git/checkouts/milli-00376cd5db949a15/03aa120/milli/src/update/words_level_positions.rs:214:13
  14:        0x1098761c4 - milli::update::words_level_positions::WordsLevelPositions::execute::h1dccc411ab6ec449
                               at /Users/bb/.cargo/git/checkouts/milli-00376cd5db949a15/03aa120/milli/src/update/words_level_positions.rs:63:23
  15:        0x109568be5 - milli::update::index_documents::IndexDocuments::execute_prefix_databases::he718bd4d3aafb197
                               at /Users/bb/.cargo/git/checkouts/milli-00376cd5db949a15/03aa120/milli/src/update/index_documents/mod.rs:413:9
  16:        0x109568be5 - milli::update::index_documents::IndexDocuments::execute_raw::h08550240b07c4f65
                               at /Users/bb/.cargo/git/checkouts/milli-00376cd5db949a15/03aa120/milli/src/update/index_documents/mod.rs:331:9
  17:        0x109568be5 - milli::update::index_documents::IndexDocuments::execute::hd846f3ed684d1b45
                               at /Users/bb/.cargo/git/checkouts/milli-00376cd5db949a15/03aa120/milli/src/update/index_documents/mod.rs:180:9
  18:        0x109551a4e - meilisearch_http::index::updates::<impl meilisearch_http::index::Index>::update_documents_txn::h4887d9107831424f
                               at /Users/bb/src/meilisearch/MeiliSearch/meilisearch-http/src/index/updates.rs:225:30
  19:        0x109551a4e - meilisearch_http::index::updates::<impl meilisearch_http::index::Index>::update_documents::hae3df4ee12a3ca9b
                               at /Users/bb/src/meilisearch/MeiliSearch/meilisearch-http/src/index/updates.rs:183:22
  20:        0x1095c9c1c - meilisearch_http::index::update_handler::UpdateHandler::handle_update::h49d84bb34674c5cf
                               at /Users/bb/src/meilisearch/MeiliSearch/meilisearch-http/src/index/update_handler.rs:72:18
  21:        0x109445610 - meilisearch_http::index_controller::index_actor::actor::IndexActor<S>::handle_update::{{closure}}::{{closure}}::hd7194fc4792c537f
                               at /Users/bb/src/meilisearch/MeiliSearch/meilisearch-http/src/index_controller/index_actor/actor.rs:174:35
  22:        0x109445610 - <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll::h7965e70ea9b75d71
                               at /Users/bb/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/runtime/blocking/task.rs:42:21
  23:        0x10949c73b - tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}::h5e16ec0ab2e67901
                               at /Users/bb/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/runtime/task/core.rs:243:17
  24:        0x10949c73b - tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::h753e6ad12e9a34c7
                               at /Users/bb/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/loom/std/unsafe_cell.rs:14:9
  25:        0x10949c73b - tokio::runtime::task::core::CoreStage<T>::poll::hf1a4e5b849526d98
                               at /Users/bb/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/runtime/task/core.rs:233:13
  26:        0x1095f1068 - tokio::runtime::task::harness::poll_future::{{closure}}::h04e2e2773958d514
                               at /Users/bb/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/runtime/task/harness.rs:427:23
  27:        0x1095f1068 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h80ac8c602b11c348
                               at /private/tmp/rust-20210801-17184-lxlkmx/rustc-1.54.0-src/library/std/src/panic.rs:347:9
  28:        0x1095f1068 - std::panicking::try::do_call::h34e9ca8aae51bf31
                               at /private/tmp/rust-20210801-17184-lxlkmx/rustc-1.54.0-src/library/std/src/panicking.rs:401:40
  29:        0x1095f1068 - std::panicking::try::ha52acca01a4b7cd9
                               at /private/tmp/rust-20210801-17184-lxlkmx/rustc-1.54.0-src/library/std/src/panicking.rs:365:19
  30:        0x1095f1068 - std::panic::catch_unwind::hbc1c55b6d78b1ef5
                               at /private/tmp/rust-20210801-17184-lxlkmx/rustc-1.54.0-src/library/std/src/panic.rs:434:14
  31:        0x1095f1068 - tokio::runtime::task::harness::poll_future::h43c45b81d9f2d0c8
                               at /Users/bb/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/runtime/task/harness.rs:414:19
  32:        0x1095f1068 - tokio::runtime::task::harness::Harness<T,S>::poll_inner::hf5e76355b5d486fd
                               at /Users/bb/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/runtime/task/harness.rs:89:9
  33:        0x1095f1068 - tokio::runtime::task::harness::Harness<T,S>::poll::h5ab468bad5e6844f
                               at /Users/bb/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/runtime/task/harness.rs:59:15
  34:        0x109c866f1 - tokio::runtime::task::raw::RawTask::poll::h90e923e19bdda6b6
                               at /Users/bb/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/runtime/task/raw.rs:66:18
  35:        0x109c866f1 - tokio::runtime::task::Notified<S>::run::h34015880c9542834
                               at /Users/bb/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/runtime/task/mod.rs:171:9
  36:        0x109c866f1 - tokio::runtime::blocking::pool::Inner::run::h885256fbe063a0ba
                               at /Users/bb/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/runtime/blocking/pool.rs:265:17
  37:        0x109c866f1 - tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}::h99fdba8717755392
                               at /Users/bb/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/runtime/blocking/pool.rs:245:17
  38:        0x109c866f1 - std::sys_common::backtrace::__rust_begin_short_backtrace::hbe628707e5bdb21e
                               at /private/tmp/rust-20210801-17184-lxlkmx/rustc-1.54.0-src/library/std/src/sys_common/backtrace.rs:125:18
  39:        0x109c7da31 - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::hc0e358e8b0ebb64f
                               at /private/tmp/rust-20210801-17184-lxlkmx/rustc-1.54.0-src/library/std/src/thread/mod.rs:481:17
  40:        0x109c7da31 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h3d6b0af53b7f1037
                               at /private/tmp/rust-20210801-17184-lxlkmx/rustc-1.54.0-src/library/std/src/panic.rs:347:9
  41:        0x109c7da31 - std::panicking::try::do_call::hae8896cfc9a97c29
                               at /private/tmp/rust-20210801-17184-lxlkmx/rustc-1.54.0-src/library/std/src/panicking.rs:401:40
  42:        0x109c7da31 - std::panicking::try::h675bf6cde13de7d7
                               at /private/tmp/rust-20210801-17184-lxlkmx/rustc-1.54.0-src/library/std/src/panicking.rs:365:19
  43:        0x109c7da31 - std::panic::catch_unwind::h9a91674584f9aa4b
                               at /private/tmp/rust-20210801-17184-lxlkmx/rustc-1.54.0-src/library/std/src/panic.rs:434:14
  44:        0x109c7da31 - std::thread::Builder::spawn_unchecked::{{closure}}::h536e7d8c1ea5ff47
                               at /private/tmp/rust-20210801-17184-lxlkmx/rustc-1.54.0-src/library/std/src/thread/mod.rs:480:30
  45:        0x109c7da31 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hd9198d04071ad18f
                               at /private/tmp/rust-20210801-17184-lxlkmx/rustc-1.54.0-src/library/core/src/ops/function.rs:227:5
  46:        0x109cb9ddb - std::sys::unix::thread::Thread::new::thread_start::h25d59e825ca56c21
  47:     0x7fff204a28fc - __pthread_start
```

**Comment by curquiza** [comment]
I've just tested: this branch fixes the panic with both datasets (3000 and 21000) 😄 🎉 
https://github.com/meilisearch/MeiliSearch/pull/1596

We hope this is the same on your side! If it is, the bug fix will be included in v0.21.0

**Comment by bb** [comment]
I confirmed the 21k case working in branch update-tokenizer-0.2.5 as well as in test-new-indexer.

**Comment by curquiza** [comment]
Closed by https://github.com/meilisearch/MeiliSearch/pull/1596
