### ISSUE TITLE
Whitespaces in filter causing EOI error

### ISSUE THREAD

**Issue by Primdahl26** [meilisearch/MeiliSearch#1648]
**Describe the bug**
After the release of v0.21.0, and the renaming of `facetsFilter` to `filter`, I am unable to filter items that include whitespaces. Adding items that do not include whitespaces, are filtered as expected.

**To Reproduce**
1. Search after a `filter` with a whitespace.
2. See error.

**Expected behavior**
Being able to filter with items that include whitespaces.

**Screenshots**
``` bash
fastapi  | Traceback (most recent call last):
fastapi  |   File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 373, in run_asgi
fastapi  |     result = await app(self.scope, self.receive, self.send)
fastapi  |   File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
fastapi  |     return await self.app(scope, receive, send)
fastapi  |   File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 208, in __call__
fastapi  |     await super().__call__(scope, receive, send)
fastapi  |   File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
fastapi  |     await self.middleware_stack(scope, receive, send)
fastapi  |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
fastapi  |     raise exc from None
fastapi  |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
fastapi  |     await self.app(scope, receive, _send)
fastapi  |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 78, in __call__
fastapi  |     await self.app(scope, receive, send)
fastapi  |   File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
fastapi  |     raise exc from None
fastapi  |   File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
fastapi  |     await self.app(scope, receive, sender)
fastapi  |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 580, in __call__
fastapi  |     await route.handle(scope, receive, send)
fastapi  |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 241, in handle
fastapi  |     await self.app(scope, receive, send)
fastapi  |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 52, in app
fastapi  |     response = await func(request)
fastapi  |   File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 226, in app
fastapi  |     raw_response = await run_endpoint_function(
fastapi  |   File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 159, in run_endpoint_function
fastapi  |     return await dependant.call(**values)
fastapi  |   File "/app/backend/src/./main.py", line 68, in search
fastapi  |     return client.index(f'media_{country_code}').search(user_input, {fastapi  |   File "/usr/local/lib/python3.9/site-packages/meilisearch/index.py", line 272, in search
fastapi  |     return self.http.post(
fastapi  |   File "/usr/local/lib/python3.9/site-packages/meilisearch/_httprequests.py", line 50, in post
fastapi  |     return self.send_request(requests.post, path, body)
fastapi  |   File "/usr/local/lib/python3.9/site-packages/meilisearch/_httprequests.py", line 33, in send_request
fastapi  |     return self.__validate(request)
fastapi  |   File "/usr/local/lib/python3.9/site-packages/meilisearch/_httprequests.py", line 82, in __validate
fastapi  |     raise MeiliSearchApiError(str(err), request) from err
fastapi  | meilisearch.errors.MeiliSearchApiError: MeiliSearchApiError. Error code: invalid_filter. Error message:  --> 1:27
fastapi  |   |
fastapi  | 1 | specific_provider_names=C More
fastapi  |   |                           ^---
fastapi  |   |
fastapi  |   = expected EOI, and, or or. Error documentation: https://docs.meilisearch.com/errors#invalid_filter
```
Whenever I visit the documentation referred to, I get a `404`.
https://docs.meilisearch.com/errors/#invalid_filter  
https://docs.meilisearch.com/reference/features/filtering.html

**MeiliSearch version:**
v0.21.0

**Additional context**
Meilisearch is implemented using the python SDK, in a FastAPI application.
The following URL is being fed to the FastAPI application:

``` bash
curl -X 'GET' \
  'http://localhost:1337/search/w?c=DK&g=Action&p=C%20More' \
  -H 'accept: application/json'
```

The following python code is handling the request:
``` python
@app.get('/search/{user_input}')
async def search(user_input: str,
                 c: str,
                 g: Optional[List[str]] = Query(None),
                 p: Optional[List[str]] = Query(None)):
    """
    # Our endpoint for the MeiliSearch API
    * **user_input**: Input to lookup media
    * **g**: Optional genre query
    * **p**: Optional provider query
    """
    genres = g
    providers = p
    country_code = c

    if genres and providers:
        genre_list: list[str] = [
            f'genres={genre}' for genre in genres
        ]
        provider_list: list[list[str]] = [
            [f'specific_provider_names={providers}'
             for providers in providers]
        ]

        return client.index(f'media_{country_code}').search(user_input, {
            'limit': 21,
            'filter': genre_list + provider_list
        })
    elif genres:
        return client.index(f'media_{country_code}').search(user_input, {
            'limit': 21,
            # This is using AND logic
            'filter': [f'genres={genre}' for genre in genres]
        })
    elif providers:
        return client.index(f'media_{country_code}').search(user_input, {
            'limit': 21,
            # This is using OR logic
            'filter': [[f'specific_provider_names={providers}'
                        for providers in providers]]
        })
    return client.index(f'media_{country_code}').search(user_input, {'limit': 21})

```

**Comment by Kerollmops** [comment]
Hey @Primdahl26,

Thanks for this report, I will tell the documentation team about the outdated links on [the errors page](https://docs.meilisearch.com/errors/#invalid_filter), @guimachiavelli could you please update them, please? 👀

About the error returned when you try to search for `specific_provider_names=C More` it is indeed related to the new syntax that requires that you put values into double or simple quotes. You can read more on [the new documentation page](https://docs.meilisearch.com/reference/features/filtering_and_faceted_search.html#using-filters).

If you have any issues regarding filters, ask us for help.
Have a good day 🌳

**Comment by curquiza** [comment]
I close this issue since it seems an answer has been given 🙂

**Comment by guimachiavelli** [comment]
For those monitoring this issue, the links have been fixed on the documentation site.

Thanks for notifying us!
