### ISSUE TITLE
Panic on main

### ISSUE THREAD

**Issue by irevoire** [meilisearch/meilisearch#2418]
**Describe the bug**
Meilisearch panic when I try to index movies.json.

**To Reproduce**
1. Index movies.json

**Expected behavior**
It index movies.json

**Screenshots**
<img width="500" alt="image" src="https://user-images.githubusercontent.com/7032172/169820208-233b5440-5356-47b9-a741-ee32668b2ee2.png">

**Meilisearch version:**
main

**Additional context**
```
thread '<unnamed>' panicked at 'range end index 4 out of range for slice of length 0', library/core/src/slice/index.rs:73:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/b2eed72a6fbf254e7d44942eaa121fcbed05d3fb/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/b2eed72a6fbf254e7d44942eaa121fcbed05d3fb/library/core/src/panicking.rs:142:14
   2: core::slice::index::slice_end_index_len_fail_rt
             at /rustc/b2eed72a6fbf254e7d44942eaa121fcbed05d3fb/library/core/src/slice/index.rs:73:5
   3: core::ops::function::FnOnce::call_once
             at /rustc/b2eed72a6fbf254e7d44942eaa121fcbed05d3fb/library/core/src/ops/function.rs:248:5
   4: core::intrinsics::const_eval_select
             at /rustc/b2eed72a6fbf254e7d44942eaa121fcbed05d3fb/library/core/src/intrinsics.rs:2372:5
   5: core::slice::index::slice_end_index_len_fail
             at /rustc/b2eed72a6fbf254e7d44942eaa121fcbed05d3fb/library/core/src/slice/index.rs:67:9
   6: lindera_core::connection::ConnectionCostMatrix::load
   7: lindera_ipadic::load_dictionary
   8: lindera::tokenizer::Tokenizer::with_config
   9: core::ops::function::FnOnce::call_once
  10: once_cell::imp::OnceCell<T>::initialize::{{closure}}
  11: once_cell::imp::initialize_inner
  12: once_cell::imp::OnceCell<T>::initialize
  13: <meilisearch_tokenizer::tokenizer::lindera::Lindera as meilisearch_tokenizer::tokenizer::Tokenizer>::tokenize
  14: milli::update::index_documents::extract::extract_docid_word_positions::extract_docid_word_positions
  15: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  16: std::panicking::try
  17: rayon_core::registry::in_worker
  18: milli::update::index_documents::extract::send_and_extract_flattened_documents_data
  19: <rayon::iter::map::MapFolder<C,F> as rayon::iter::plumbing::Folder<T>>::consume
  20: <rayon::iter::par_bridge::IterParallelProducer<Iter> as rayon::iter::plumbing::UnindexedProducer>::fold_with
  21: rayon::iter::plumbing::bridge_unindexed_producer_consumer
  22: std::panicking::try
  23: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
  24: rayon_core::registry::WorkerThread::wait_until_cold
  25: rayon_core::registry::ThreadBuilder::run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by irevoire** [comment]
Ok, no, that’s my fault. I remember now! I patched my cached version of lindera two weeks ago so it would compile without the network.
