### ISSUE TITLE
Fix a test on the dump that is failling on Windows only

### ISSUE THREAD

**Issue by Kerollmops** [meilisearch/meilisearch#2994]
We were able to enable most of the tests on Windows but there is [one remaining test that is not passing](https://github.com/meilisearch/meilisearch/actions/runs/3337124216/jobs/5523076058#step:5:586). It returns an error about a file being opened by multiple processes at the same time.

```
 failures:

---- dumps::import_dump_v1 stdout ----
thread 'dumps::import_dump_v1' panicked at 'assertion failed: `(left == right)`
  left: `"The process cannot access the file because it is being used by another process. (os error 32)"`,
 right: `"The version 1 of the dumps is not supported anymore. You can re-export your dump from a version between 0.21 and 0.24, or start fresh from a version 0.25 onwards."`', meilisearch-http\tests\dumps\mod.rs:22:9
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library\std\src\panicking.rs:584
   1: core::panicking::panic_fmt
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library\core\src\panicking.rs:142
   2: core::fmt::Arguments::new_v1
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library\core\src\fmt\mod.rs:394
   3: core::panicking::assert_failed_inner
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library\core\src\panicking.rs:224
   4: _guard_xfg_dispatch_icall_nop
   5: <tar::error::TarError as core::fmt::Display>::fmt
   6: <meilisearch_http::analytics::mock_analytics::MockAnalytics as meilisearch_http::analytics::Analytics>::add_documents
   7: core::ops::function::FnOnce::call_once
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library\core\src\ops\function.rs:248
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

If we are able to fix this one, no more tests will be conditionally ignored on this platform anymore 🎉

**Comment by Kerollmops** [comment]
It seems fixed by now (I cannot find when). But there are no more tests that run on every platform but Windows 🎉

**Comment by irevoire** [comment]
For future reference, iirc it started working again when we enabled back the support of the dumpv1 (yeah I know, that’s strange because importing a dump was just returning an error message)
