### ISSUE TITLE
Value as a key breaks Web UI

### ISSUE THREAD

**Issue by eikooc** [meilisearch/meilisearch#3291]
**Describe the bug**
When I have a property named `value` in a nested JSON structure, the Web UI breaks.

**To Reproduce**
1. Start MeiliSearch and the dashboard
2. Go to http://localhost:7700
3. Add a json value on a key. e.g. { "foo": { "some_property": "abc", "value": "bar" }
4. The web UI breaks because the `value` is interpreted as a link.

**Expected behavior**
I expect to be able to have a data structure that contains keys with the name `value`, so I don't have to change my data structure to be used in Meilisearch

**Meilisearch version:** [e.g. v0.30.4]

**Additional context**
Error in browser:
```
TypeError: t.match is not a function
    at Zl (Hit.js:163:21)
    at oo (react-dom.production.min.js:157:137)
    at Qs (react-dom.production.min.js:267:460)
    at Pu (react-dom.production.min.js:250:347)
    at Cu (react-dom.production.min.js:250:278)
    at ju (react-dom.production.min.js:250:138)
    at gu (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at Ki (react-dom.production.min.js:122:325)
```

**Comment by curquiza** [comment]
Hello @eikooc 
Thanks for the report

Just to be sure I understand correctly, is this bug appear only in the dashboard, I mean, is it only an error of display? Can you still use Meilisearch, aka the API?

**Comment by eikooc** [comment]
Yes, it is only the dashboard. The API works fine

**Comment by curquiza** [comment]
Ok, then I will move this issue to the right repository 😇
