### ISSUE TITLE
Benchmarks running on `main` are failing

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch#3386]
Since we merged [milli into Meilisearch](https://github.com/meilisearch/meilisearch/pull/3346), Benchmark running on `main` (for every push on `main`) are failing see:
https://github.com/meilisearch/meilisearch/actions/workflows/push_benchmarks_search_wiki.yml

```
Run BetaHuhn/do-spaces-action@v2
/home/meili/actions-runner/_work/_actions/BetaHuhn/do-spaces-action/v2/dist/index.js:1366
            throw new Error("Input `".concat(options.key, "` is required but was not provided."));
            ^

Error: Input `space_name` is required but was not provided.
    at getInput (/home/meili/actions-runner/_work/_actions/BetaHuhn/do-spaces-action/v2/dist/index.js:1366:19)
    at Object.34570 (/home/meili/actions-runner/_work/_actions/BetaHuhn/do-spaces-action/v2/dist/index.js:35713:13)
    at __nccwpck_require__ (/home/meili/actions-runner/_work/_actions/BetaHuhn/do-spaces-action/v2/dist/index.js:41493:43)
    at /home/meili/actions-runner/_work/_actions/BetaHuhn/do-spaces-action/v2/dist/index.js:41516:16
    at /home/meili/actions-runner/_work/_actions/BetaHuhn/do-spaces-action/v2/dist/index.js:41601:3
    at Object.<anonymous> (/home/meili/actions-runner/_work/_actions/BetaHuhn/do-spaces-action/v2/dist/index.js:41604:12)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
```

**Comment by curquiza** [comment]
Doing a test right now with https://github.com/meilisearch/meilisearch/actions/runs/4316564105
-> the authentication secrets for the CI were missing...

**Comment by curquiza** [comment]
It now works again, it was indeed an issue with secrets, my bad!
Closing this with joy!
