### ISSUE TITLE
Unwrap error after updating `rankedRules`

### ISSUE THREAD

**Issue by curquiza** [meilisearch/MeiliSearch#369]
My documents:
```json
[
    {
        "objectId": 42,
        "title": "The Hitchhiker's Guide to the Galaxy"
    },
    {
        "objectId": 4,
        "title": "Harry Potter and the Half-Blood Prince"
    },
    {
        "objectId": 123,
        "title": "Pride and Prejudice"
    },
    {
        "objectId": 1344,
        "title": "The Hobbit"
    },
    {
        "objectId": 456,
        "title": "Le Petit Prince"
    },
    {
        "objectId": 1,
        "title": "Alice In Wonderland"
    }
]
```
Steps:
- route `POST /indexes/:uid/settings` with body: `{"rankingRules": {"objectId": "asc" }}`
- search 'prince' with search route on this index.

It crashes with :
```
thread 'tokio-runtime-worker-2' panicked at 'called `Result::unwrap()` on an `Err` value: AttributeNotRegisteredForRanking', src/libcore/result.rs:1165:5
thread 'tokio-runtime-worker-3' panicked at 'called `Result::unwrap()` on an `Err` value: AttributeNotRegisteredForRanking', src/libcore/result.rs:1165:5
```

**Comment by Kerollmops** [comment]
I reopen because it seems like you missed something.

https://github.com/meilisearch/MeiliSearch/blob/df7dc5440971b6a09af686501e0e3f51d910c58e/meilisearch-http/src/helpers/meilisearch.rs#L325-L334
