### ISSUE TITLE
milli panic: `The ranking rule fid did not sort its bucket exhaustively`

### ISSUE THREAD

**Issue by GregoryConrad** [meilisearch/meilisearch#3728]
I get this using `milli` on `main` right now at the moment after the big search refactor.

Will update this issue with a reproducible example if I can create one in pure Rust.

**Comment by nitrag** [comment]
I think this is not only impactly my M1 development environment but also our ARM64 cloud deployment.

```
 thread 'tokio-runtime-worker' panicked at 'The ranking rule fid did not sort its bucket exhaustively', milli/src/search/new/bucket_sort.rs:162:13
  stack backtrace:
    0: rust_begin_unwind
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:579:5
    1: core::panicking::panic_fmt
              at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:64:14
    2: milli::search::new::bucket_sort::bucket_sort
    3: milli::search::new::execute_search
    4: milli::search::Search::execute
    5: meilisearch::search::perform_search
    6: tokio::runtime::task::raw::poll

```

Search works for some words but errors out for others like `us`. What is the workaround? I started with an empty database, added documents, then I get this. Version `1.3.1`.

**Comment by nitrag** [comment]
Never mind, this fails in the AWS EC2 Community AMI (`567502172578/Meilisearch-v1.3.0-Debian-11`) on a `t3.small`. This works in the hosted/cloud offering but not in self-hosted. @dureuill any thoughts?
