### ISSUE TITLE
Panic when using Experimental VectorSearch

### ISSUE THREAD

**Issue by alallema** [meilisearch/meilisearch#3923]
**Describe the bug**
A "500 Internal Server Error" error is received when executing a vector search:
```
[2023-07-12T14:01:22Z WARN meilisearch::search] Ignoring the query string `q` when used with the `vector` parameter.
thread 'tokio-runtime-worker' panicked at 'source slice length (80) does not match destination slice length (84)', /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hnsw-0.11.0/src/hnsw/hnsw_const.rs:308:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**To Reproduce**
Using Langchain Meilisearch Vectorstore, to add the Meilisearch documentation through Blazy
1. Go to this [PR](https://github.com/alallema/langchain/tree/meilisearch_vectorstore) for getting the Langchain Vectorstore code
2. Go to this repo to get the blazy-build(https://github.com/alallema/blazy-build/tree/meilisearch-vector-store)
3. Change the Langchain path from `requirement.txt` to your own (ex: /Users/my_own_directory/langchain)
4. Follow the README.md
5. Update the FilterableAttribute with ```[
	"_semanticScore"
]```
6. At some point the search request by `vector` or `query`, with or without `limits`, and with or without filters, start to generate 500 errors.

**Meilisearch version:**
[v1.3.0-rc.1](https://github.com/meilisearch/meilisearch/releases/tag/v1.3.0-rc.1)

**Additional context**
The error has happened many times, but I am unable to find the exact steps to reproduce them exactly.
I also had at least 4 indexes containing vectors at this time.

**Comment by Kerollmops** [comment]
Thank you for the report, @alallema!

The issue comes from the library's internal code when we search. [I opened an issue](https://github.com/rust-cv/hnsw/issues/31) on the dedicated repository.

**Comment by alallema** [comment]
Thank you @Kerollmops, for finding the source of this error 🚀 
I'm a little late, but I have the complete trace in case it helps:
```
[2023-07-24T09:40:10Z WARN  meilisearch::search] Ignoring the query string `q` when used with the `vector` parameter.
thread 'tokio-runtime-worker' panicked at 'source slice length (42) does not match destination slice length (43)', /cargo/registry/src/index.crates.io-6f17d22bba15001f/hnsw-0.11.0/src/hnsw/hnsw_const.rs:308:14
stack backtrace:
   0:     0xaaaad0362638 - std::backtrace_rs::backtrace::libunwind::trace::h5ba5357b9a083fa0
                               at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0xaaaad0362638 - std::backtrace_rs::backtrace::trace_unsynchronized::h50209a046e340266
                               at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0xaaaad0362638 - std::sys_common::backtrace::_print_fmt::hc1f0fe6a809af61e
                               at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/sys_common/backtrace.rs:65:5
   3:     0xaaaad0362638 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1dc727a23fab6b83
                               at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/sys_common/backtrace.rs:44:22
   4:     0xaaaad0388420 - core::fmt::rt::Argument::fmt::hdb7178e51bb87859
                               at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/fmt/rt.rs:138:9
   5:     0xaaaad0388420 - core::fmt::write::h93016cb9b016717f
                               at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/fmt/mod.rs:1094:21
   6:     0xaaaad035f1a0 - std::io::Write::write_fmt::hd05d9d1974faeacd
                               at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/io/mod.rs:1713:15
   7:     0xaaaad0362484 - std::sys_common::backtrace::_print::h63e8991360658009
                               at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/sys_common/backtrace.rs:47:5
   8:     0xaaaad0362484 - std::sys_common::backtrace::print::hc0e015b240e04d4b
                               at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/sys_common/backtrace.rs:34:9
   9:     0xaaaad0363788 - std::panicking::default_hook::{{closure}}::h578d14e5d7d719df
  10:     0xaaaad0363578 - std::panicking::default_hook::h79df13a143e47d78
                               at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:288:9
  11:     0xaaaad0363c78 - std::panicking::rust_panic_with_hook::hacc6c775e464554f
                               at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:705:13
  12:     0xaaaad0363b40 - std::panicking::begin_panic_handler::{{closure}}::hc234bdc87cdab675
                               at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:597:13
  13:     0xaaaad0362a44 - std::sys_common::backtrace::__rust_end_short_backtrace::h413cb82ec8fa424a
                               at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/sys_common/backtrace.rs:151:18
  14:     0xaaaad03638a4 - rust_begin_unwind
                               at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:593:5
  15:     0xaaaacf6b1a54 - core::panicking::panic_fmt::h931044ebf9f23425
                               at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/panicking.rs:67:14
  16:     0xaaaacf6b1f08 - core::slice::<impl [T]>::copy_from_slice::len_mismatch_fail::hcd38a5a068be5a77
                               at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/slice/mod.rs:3602:13
  17:     0xaaaacff154f0 - milli::search::new::execute_search::h18a3c62dd3ffe0d0
  18:     0xaaaacff15b38 - milli::search::Search::execute::h2191afc7cfb6d0bd
  19:     0xaaaacf994e5c - meilisearch::search::perform_search::h64cad8a1807336a7
  20:     0xaaaacf85f128 - tokio::runtime::task::raw::poll::hd0db7ea4c7199360
  21:     0xaaaad0314658 - std::sys_common::backtrace::__rust_begin_short_backtrace::hbd5cb8926ae72d4b
  22:     0xaaaad0315a04 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h794fbdaaa10bb772
  23:     0xaaaad0368078 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hf086f9e2ccb58764
                               at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/alloc/src/boxed.rs:1985:9
  24:     0xaaaad0368078 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h7d8a44b475ea4a2f
                               at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/alloc/src/boxed.rs:1985:9
  25:     0xaaaad0368078 - std::sys::unix::thread::Thread::new::thread_start::h9739608577c2d86d
                               at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/sys/unix/thread.rs:108:17
  26:     0xffff89aed5c8 - <unknown>
  27:     0xffff89b55d1c - <unknown>
  28:                0x0 - <unknown>
```

**Comment by Kerollmops** [comment]
Hey @alallema 👋

Thank you for the backtrace. I will investigate and fix the bug on our HNSW dependency this week.

Have a nice day 🍨

**Comment by gillian-meilisearch** [comment]
The linked PR has been merged so will close this out, thanks for the info @alallema :)
