### ISSUE TITLE
Error message: JSON payload is larger than allowed 

### ISSUE THREAD

**Issue by Nikopol484** [meilisearch/meilisearch#4301]
I got next error when I'm try to upload synonyms

Error message: JSON payload (4696120 bytes) is larger than allowed (limit: 2097152 bytes)
Full error:

`Traceback (most recent call last):
  File "/home/administrator/.local/lib/python3.8/site-packages/meilisearch/_httprequests.py", line 107, in __validate
    request.raise_for_status()
  File "/home/administrator/.local/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://10.0.1.61:7700/indexes/sello_prod/settings/synonyms

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "algolia_synonyms.py", line 36, in <module>
    m_index.update_synonyms(meili_syn)
  File "/home/administrator/.local/lib/python3.8/site-packages/meilisearch/index.py", line 1253, in update_synonyms
    task = self.http.put(self.__settings_url_for(self.config.paths.synonyms), body)
  File "/home/administrator/.local/lib/python3.8/site-packages/meilisearch/_httprequests.py", line 89, in put
    return self.send_request(requests.put, path, body, content_type)
  File "/home/administrator/.local/lib/python3.8/site-packages/meilisearch/_httprequests.py", line 57, in send_request
    return self.__validate(request)
  File "/home/administrator/.local/lib/python3.8/site-packages/meilisearch/_httprequests.py", line 110, in __validate
    raise MeilisearchApiError(str(err), request) from err
meilisearch.errors.MeilisearchApiError: MeilisearchApiError. Error code: internal. Error message: JSON payload (4696120 bytes) is larger than allowed (limit: 2097152 bytes). Error documentation: https://docs.meilisearch.com/errors#internal Error type: internal`

Meilisearch version 1.4.2
In toml file 
http_payload_size_limit = "1Gb"

**Comment by Nikopol484** [comment]
[meilisearch.toml.txt](https://github.com/meilisearch/meilisearch/files/13877185/meilisearch.toml.txt)
Config file
[synonyms.json](https://github.com/meilisearch/meilisearch/files/13877187/synonyms.json)
Payload
Call PUT method {{url}}/indexes/{{indexUID}}/settings/synonyms
via python meilisearch library (0.28.4)

**Comment by curquiza** [comment]
Hello @Nikopol484 

This issue has been fixed recently and [the fix](https://github.com/meilisearch/meilisearch/pull/4231) will be available in a stable release on Monday 😊
In the meantime, if you really need a quick fix, you can already test our release candidates (RC) [here](https://github.com/meilisearch/meilisearch/releases)

**Comment by Nikopol484** [comment]
Thanks
