### ISSUE TITLE
Broken CI running with "almost all features"

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch#4816]
Our scheduled CI is failing for this reason

<details>
<summary>Click to get the logs</summary>

```
failures:

---- search::multi::federation_formatting stdout ----
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Snapshot Summary ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Snapshot: federation_formatting
Source: meilisearch/tests/search/multi.rs:3258
────────────────────────────────────────────────────────────────────────────────
Expression: response
────────────────────────────────────────────────────────────────────────────────
-old snapshot
+new results
────────────┬───────────────────────────────────────────────────────────────────
    0     0 │ {
    1     1 │   "hits": [
    2     2 │     {
    3       │-      "title": "Gläss",
    4       │-      "_federation": {
    5       │-        "indexUid": "test",
    6       │-        "queriesPosition": 0,
    7       │-        "weightedRankingScore": 1.0
    8       │-      },
    9       │-      "_formatted": {
   10       │-        "title": "<em>Gläss</em>"
   11       │-      }
   12       │-    },
   13       │-    {
   14     3 │       "id": 852,
   15     4 │       "_federation": {
   16     5 │         "indexUid": "nested",
   17     6 │         "queriesPosition": 2,
┈┈┈┈┈┈┈┈┈┈┈┈┼┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
  111   100 │         "title": "<em>Badman</em>"
  112   101 │       }
  113   102 │     },
  114   103 │     {
        104 │+      "title": "Gläss",
        105 │+      "_federation": {
        106 │+        "indexUid": "test",
        107 │+        "queriesPosition": 0,
        108 │+        "weightedRankingScore": 0.4621212121212121
        109 │+      },
        110 │+      "_formatted": {
        111 │+        "title": "<em>Gläss</em>"
        112 │+      }
        113 │+    },
        114 │+    {
  115   115 │       "title": "How to Train Your Dragon: The Hidden World",
  116   116 │       "_federation": {
  117   117 │         "indexUid": "test",
  118   118 │         "queriesPosition": 6,
────────────┴───────────────────────────────────────────────────────────────────
Stopped on the first failure. Run `cargo insta test` to run all snapshots.
thread 'search::multi::federation_formatting' panicked at /github/home/.cargo/registry/src/index.crates.io-6f17d22bba15001f/insta-1.39.0/src/runtime.rs:562:9:
snapshot assertion for 'federation_formatting' failed in line 3258
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: insta::runtime::assert_snapshot
   3: integration::search::multi::federation_formatting::{{closure}}
   4: tokio::task::local::LocalSet::run_until::{{closure}}
   5: core::ops::function::FnOnce::call_once
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

---- search::multi::federation_limit_offset stdout ----
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Snapshot Summary ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Snapshot: federation_limit_offset
Source: meilisearch/tests/search/multi.rs:2940
────────────────────────────────────────────────────────────────────────────────
Expression: response
────────────────────────────────────────────────────────────────────────────────
-old snapshot
+new results
────────────┬───────────────────────────────────────────────────────────────────
    0     0 │ {
    1     1 │   "hits": [
    2     2 │     {
    3       │-      "title": "Gläss",
    4       │-      "_federation": {
    5       │-        "indexUid": "test",
    6       │-        "queriesPosition": 0,
    7       │-        "weightedRankingScore": 1.0
    8       │-      }
    9       │-    },
   10       │-    {
   11     3 │       "id": 852,
   12     4 │       "_federation": {
   13     5 │         "indexUid": "nested",
   14     6 │         "queriesPosition": 2,
┈┈┈┈┈┈┈┈┈┈┈┈┼┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
   87    79 │         "weightedRankingScore": 0.5
   88    80 │       }
   89    81 │     },
   90    82 │     {
         83 │+      "title": "Gläss",
         84 │+      "_federation": {
         85 │+        "indexUid": "test",
         86 │+        "queriesPosition": 0,
         87 │+        "weightedRankingScore": 0.4621212121212121
         88 │+      }
         89 │+    },
         90 │+    {
   91    91 │       "title": "How to Train Your Dragon: The Hidden World",
   92    92 │       "_federation": {
   93    93 │         "indexUid": "test",
   94    94 │         "queriesPosition": 6,
────────────┴───────────────────────────────────────────────────────────────────
Stopped on the first failure. Run `cargo insta test` to run all snapshots.
thread 'search::multi::federation_limit_offset' panicked at /github/home/.cargo/registry/src/index.crates.io-6f17d22bba15001f/insta-1.39.0/src/runtime.rs:562:9:
snapshot assertion for 'federation_limit_offset' failed in line 2940
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: insta::runtime::assert_snapshot
   3: integration::search::multi::federation_limit_offset::{{closure}}
   4: tokio::task::local::LocalSet::run_until::{{closure}}
   5: core::ops::function::FnOnce::call_once
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

---- search::multi::federation_multiple_search_multiple_indexes stdout ----
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Snapshot Summary ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Snapshot: federation_multiple_search_multiple_indexes
Source: meilisearch/tests/search/multi.rs:670
────────────────────────────────────────────────────────────────────────────────
Expression: response
────────────────────────────────────────────────────────────────────────────────
-old snapshot
+new results
────────────┬───────────────────────────────────────────────────────────────────
    0     0 │ {
    1     1 │   "hits": [
    2     2 │     {
    3       │-      "title": "Gläss",
    4       │-      "id": "450465",
    5       │-      "_vectors": {
    6       │-        "manual": [
    7       │-          -100.0,
    8       │-          340.0,
    9       │-          90.0
   10       │-        ]
   11       │-      },
   12       │-      "_federation": {
   13       │-        "indexUid": "test",
   14       │-        "queriesPosition": 0,
   15       │-        "weightedRankingScore": 1.0
   16       │-      }
   17       │-    },
   18       │-    {
   19     3 │       "id": 852,
   20     4 │       "father": "jean",
   21     5 │       "mother": "michelle",
   22     6 │       "doggos": [
┈┈┈┈┈┈┈┈┈┈┈┈┼┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
  178   162 │         "weightedRankingScore": 0.5
  179   163 │       }
  180   164 │     },
  181   165 │     {
        166 │+      "title": "Gläss",
        167 │+      "id": "450465",
        168 │+      "_vectors": {
        169 │+        "manual": [
        170 │+          -100.0,
        171 │+          340.0,
        172 │+          90.0
        173 │+        ]
        174 │+      },
        175 │+      "_federation": {
        176 │+        "indexUid": "test",
        177 │+        "queriesPosition": 0,
        178 │+        "weightedRankingScore": 0.4621212121212121
        179 │+      }
        180 │+    },
        181 │+    {
  182   182 │       "title": "How to Train Your Dragon: The Hidden World",
  183   183 │       "id": "166428",
  184   184 │       "_vectors": {
  185   185 │         "manual": [
────────────┴───────────────────────────────────────────────────────────────────
Stopped on the first failure. Run `cargo insta test` to run all snapshots.
thread 'search::multi::federation_multiple_search_multiple_indexes' panicked at /github/home/.cargo/registry/src/index.crates.io-6f17d22bba15001f/insta-1.39.0/src/runtime.rs:562:9:
snapshot assertion for 'federation_multiple_search_multiple_indexes' failed in line 670
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: insta::runtime::assert_snapshot
   3: integration::search::multi::federation_multiple_search_multiple_indexes::{{closure}}
   4: tokio::task::local::LocalSet::run_until::{{closure}}
   5: core::ops::function::FnOnce::call_once
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

---- search::multi::federation_single_search_single_index stdout ----
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Snapshot Summary ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Snapshot: federation_single_search_single_index
Source: meilisearch/tests/search/multi.rs:165
────────────────────────────────────────────────────────────────────────────────
Expression: response
────────────────────────────────────────────────────────────────────────────────
-old snapshot
+new results
────────────┬───────────────────────────────────────────────────────────────────
   11    11 │       },
   12    12 │       "_federation": {
   13    13 │         "indexUid": "test",
   14    14 │         "queriesPosition": 0,
   15       │-        "weightedRankingScore": 1.0
         15 │+        "weightedRankingScore": 0.4621212121212121
   16    16 │       }
   17    17 │     }
   18    18 │   ],
   19    19 │   "processingTimeMs": "[time]",
────────────┴───────────────────────────────────────────────────────────────────
Stopped on the first failure. Run `cargo insta test` to run all snapshots.
thread 'search::multi::federation_single_search_single_index' panicked at /github/home/.cargo/registry/src/index.crates.io-6f17d22bba15001f/insta-1.39.0/src/runtime.rs:562:9:
snapshot assertion for 'federation_single_search_single_index' failed in line 165
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: insta::runtime::assert_snapshot
   3: tokio::task::local::LocalSet::run_until::{{closure}}
   4: core::ops::function::FnOnce::call_once
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

---- search::multi::federation_two_search_single_index stdout ----
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Snapshot Summary ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Snapshot: federation_two_search_single_index
Source: meilisearch/tests/search/multi.rs:284
────────────────────────────────────────────────────────────────────────────────
Expression: response
────────────────────────────────────────────────────────────────────────────────
-old snapshot
+new results
────────────┬───────────────────────────────────────────────────────────────────
    0     0 │ {
    1     1 │   "hits": [
    2     2 │     {
    3       │-      "title": "Gläss",
    4       │-      "id": "450465",
    5       │-      "_vectors": {
    6       │-        "manual": [
    7       │-          -100.0,
    8       │-          340.0,
    9       │-          90.0
   10       │-        ]
   11       │-      },
   12       │-      "_federation": {
   13       │-        "indexUid": "test",
   14       │-        "queriesPosition": 0,
   15       │-        "weightedRankingScore": 1.0
   16       │-      }
   17       │-    },
   18       │-    {
   19     3 │       "title": "Captain Marvel",
   20     4 │       "id": "299537",
   21     5 │       "_vectors": {
   22     6 │         "manual": [
┈┈┈┈┈┈┈┈┈┈┈┈┼┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
   29    13 │         "indexUid": "test",
   30    14 │         "queriesPosition": 1,
   31    15 │         "weightedRankingScore": 0.9848484848484848
   32    16 │       }
         17 │+    },
         18 │+    {
         19 │+      "title": "Gläss",
         20 │+      "id": "450465",
         21 │+      "_vectors": {
         22 │+        "manual": [
         23 │+          -100.0,
         24 │+          340.0,
         25 │+          90.0
         26 │+        ]
         27 │+      },
         28 │+      "_federation": {
         29 │+        "indexUid": "test",
         30 │+        "queriesPosition": 0,
         31 │+        "weightedRankingScore": 0.4621212121212121
         32 │+      }
   33    33 │     }
   34    34 │   ],
   35    35 │   "processingTimeMs": "[time]",
   36    36 │   "limit": 20,
────────────┴───────────────────────────────────────────────────────────────────
Stopped on the first failure. Run `cargo insta test` to run all snapshots.
thread 'search::multi::federation_two_search_single_index' panicked at /github/home/.cargo/registry/src/index.crates.io-6f17d22bba15001f/insta-1.39.0/src/runtime.rs:562:9:
snapshot assertion for 'federation_two_search_single_index' failed in line 284
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: insta::runtime::assert_snapshot
   3: tokio::task::local::LocalSet::run_until::{{closure}}
   4: core::ops::function::FnOnce::call_once
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

---- search::multi::federation_two_search_two_indexes stdout ----
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Snapshot Summary ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Snapshot: federation_two_search_two_indexes
Source: meilisearch/tests/search/multi.rs:552
────────────────────────────────────────────────────────────────────────────────
Expression: response
────────────────────────────────────────────────────────────────────────────────
-old snapshot
+new results
────────────┬───────────────────────────────────────────────────────────────────
    0     0 │ {
    1     1 │   "hits": [
    2     2 │     {
    3       │-      "title": "Gläss",
    4       │-      "id": "450465",
    5       │-      "_vectors": {
    6       │-        "manual": [
    7       │-          -100.0,
    8       │-          340.0,
    9       │-          90.0
   10       │-        ]
   11       │-      },
   12       │-      "_federation": {
   13       │-        "indexUid": "test",
   14       │-        "queriesPosition": 0,
   15       │-        "weightedRankingScore": 1.0
   16       │-      }
   17       │-    },
   18       │-    {
   19     3 │       "id": 852,
   20     4 │       "father": "jean",
   21     5 │       "mother": "michelle",
   22     6 │       "doggos": [
┈┈┈┈┈┈┈┈┈┈┈┈┼┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
   68    52 │         "indexUid": "nested",
   69    53 │         "queriesPosition": 1,
   70    54 │         "weightedRankingScore": 0.7803030303030303
   71    55 │       }
         56 │+    },
         57 │+    {
         58 │+      "title": "Gläss",
         59 │+      "id": "450465",
         60 │+      "_vectors": {
         61 │+        "manual": [
         62 │+          -100.0,
         63 │+          340.0,
         64 │+          90.0
         65 │+        ]
         66 │+      },
         67 │+      "_federation": {
         68 │+        "indexUid": "test",
         69 │+        "queriesPosition": 0,
         70 │+        "weightedRankingScore": 0.4621212121212121
         71 │+      }
   72    72 │     }
   73    73 │   ],
   74    74 │   "processingTimeMs": "[time]",
   75    75 │   "limit": 20,
────────────┴───────────────────────────────────────────────────────────────────
Stopped on the first failure. Run `cargo insta test` to run all snapshots.
thread 'search::multi::federation_two_search_two_indexes' panicked at /github/home/.cargo/registry/src/index.crates.io-6f17d22bba15001f/insta-1.39.0/src/runtime.rs:562:9:
snapshot assertion for 'federation_two_search_two_indexes' failed in line 552
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: insta::runtime::assert_snapshot
   3: tokio::task::local::LocalSet::run_until::{{closure}}
   4: core::ops::function::FnOnce::call_once
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    search::multi::federation_formatting
    search::multi::federation_limit_offset
    search::multi::federation_multiple_search_multiple_indexes
    search::multi::federation_single_search_single_index
    search::multi::federation_two_search_single_index
    search::multi::federation_two_search_two_indexes

test result: FAILED. 592 passed; 6 failed; 0 ignored; 0 measured; 0 filtered out; finished in 93.70s
```

</details>

Or check directly the CI: https://github.com/meilisearch/meilisearch/actions/runs/10034978531/job/27730317555

**Comment by curquiza** [comment]
Closed by #4881
