### ISSUE TITLE
Internal error when run edit function on movies documents in v1.10.2

### ISSUE THREAD

**Issue by Ja7ad** [meilisearch/meilisearch#4956]
**Describe the bug**
Base on this [notion guide](https://meilisearch.notion.site/Update-Documents-by-Function-0cff8fea7655436592e7c8a6de932062) I call edit documents by function and got internal error.

```shell
curl http://localhost:7700/indexes/movies/documents/edit \
  -H 'content-type: application/json' \
  -d '{
    "filter": "id > 3000",
    "function": "doc.title = `✨ ${doc.title.to_upper()} ✨`"
  }'
```

**Expected behavior**

Server log:

```shell
2024-09-25T07:11:29.563769Z ERROR meilisearch: info=panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/rhai-1.19.0/src/engine.rs:347:58: called `Option::unwrap()` on a `None` value
2024-09-25T07:11:29.634669Z ERROR meilisearch: info=panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/rhai-1.19.0/src/engine.rs:347:58: called `Option::unwrap()` on a `None` value
2024-09-25T07:11:29.766880Z ERROR meilisearch: info=panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-par-bridge-0.1.0/src/lib.rs:47:5: a scoped thread panicked
```
Task details

```json
 {
            "uid": 2,
            "indexUid": "movies",
            "status": "failed",
            "type": "documentEdition",
            "canceledBy": null,
            "details": {
                "editedDocuments": 0,
                "deletedDocuments": null,
                "originalFilter": "\"id > 3000\"",
                "context": null,
                "function": "doc.title = `✨ ${doc.title.to_upper()} ✨`"
            },
            "error": {
                "message": "An unexpected crash occurred when processing the task.",
                "code": "internal",
                "type": "internal",
                "link": "https://docs.meilisearch.com/errors#internal"
            },
            "duration": "PT0.391994763S",
            "enqueuedAt": "2024-09-25T07:11:29.371295421Z",
            "startedAt": "2024-09-25T07:11:29.380739658Z",
            "finishedAt": "2024-09-25T07:11:29.772734421Z"
        }
```

**Meilisearch version:**
v1.10.2

**Comment by irevoire** [comment]
Hey @Ja7ad, the bug seems to be fixed.
I’ll integrate the fix into the next rc. It would be awesome if you could try it out once it’s released.

Thanks for finding and reporting the issue 🚀
