### ISSUE TITLE
ERROR meilisearch: info=panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/arroy-0.4.0index.crates.io-6f17d22bba15001f/arroy-0.4.0/src/parallel.rs:205:13: assertion `left == right` failed   left: 3077  right: 1541

### ISSUE THREAD

**Issue by mohamed99akram** [meilisearch/meilisearch#5165]
**Describe the bug**
I tried to add documents and got the following error
ERROR meilisearch: info=panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/arroy-0.4.0index.crates.io-6f17d22bba15001f/arroy-0.4.0/src/parallel.rs:205:13: assertion `left == right` failed   left: 3077  right: 1541
I am using the vectorstore experimental feature. I am not sure what caused the problem. did I add two dimensions of embeddings? I am not sure

**To Reproduce**
No idea why it happened.

**Expected behavior**

**Screenshots**
ERROR meilisearch: info=panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/arroy-0.4.0index.crates.io-6f17d22bba15001f/arroy-0.4.0/src/parallel.rs:205:13: assertion `left == right` failed   left: 3077  right: 1541

**Meilisearch version:**
[e.g. v1.10.1]

**Additional context**
Additional information that may be relevant to the issue.
I am using it on kubernetes.  using statefulsets.

**Comment by mohamed99akram** [comment]
Sorry for being unclear.
- Yes, it is v1.10.1
- I actually destroyed the instance and created a new one as I thought upgrading would solve something
- Yes it is a kubernetes storage class that is offered by the cloud provider
- I had about 700 documents before deleting the index.
- Embedding model used has 768 dimensions!

**Comment by mohamed99akram** [comment]
nvm, hopefully it is solved in the new version

**Comment by irevoire** [comment]
Hey, no it's not (I know it I wrote the code that triggered the assert for both version).
But I really can't help you if you don't know the kind of storage you're using sorry :confounded:
