### ISSUE TITLE
Error during delete

### ISSUE THREAD

**Issue by djKooks** [meilisearch/MeiliSearch#687]
Hello,
I was trying to refresh storage after update, but faced with some error like:
```
[2020-05-17T12:14:31Z INFO  actix_web::middleware::logger] 127.0.0.1:62766 "DELETE /indexes HTTP/1.1" 404 0 "-" "curl/7.64.1" 0.000568
[2020-05-17T12:14:35Z INFO  actix_web::middleware::logger] 127.0.0.1:62768 "GET /indexes/movies/documents HTTP/1.1" 200 307 "-" "curl/7.64.1" 0.000339
^[[A[2020-05-17T12:15:12Z INFO  actix_web::middleware::logger] 127.0.0.1:62773 "DELETE /indexes/movies/documents HTTP/1.1" 202 14 "-" "curl/7.64.1" 0.000599
thread 'actix-rt:worker:5' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', /Users/kwangin.jung/workspace/etc/rust/MeiliSearch/meilisearch-core/src/database.rs:300:17
thread 'actix-rt:worker:6' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', /Users/kwangin.jung/workspace/etc/rust/MeiliSearch/meilisearch-core/src/database.rs:237:28
thread 'actix-rt:worker:7' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', /Users/kwangin.jung/workspace/etc/rust/MeiliSearch/meilisearch-core/src/database.rs:237:28
```
After this situation, all request is returning error.
How can I fix it?

Also, is there a simple way to refresh all documents/indexes?

**Comment by MarinPostma** [comment]
Hello @djKooks, can you give us repro steps? thanks!

**Comment by djKooks** [comment]
@MarinPostma I've POST 'movies.json' to `indexes/movies/document` twice, try GET 'document' several times, and try 'delete' as you see in log.

**Comment by MarinPostma** [comment]
@djKooks sorry, this issue was forgotten, do you still have this problem on 0.11? if not, can you close this issue? thanks!
