### ISSUE TITLE
Compilation issue on windows

### ISSUE THREAD

**Issue by anborg** [meilisearch/MeiliSearch#851]
I tried compiling meili in windows, gives a false error "disk has no space".  Please let me know how do I overcome this.

I notice this: I dont have a d: drive in my laptop, but this path shows d:
Where is it coming from?

invoke_main
             at **d:\agent\_work**\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  49: __scrt_common_main_seh
             at d:\agent\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288

```C:\apps\env_winos\bin>rustup show
Default host: x86_64-pc-windows-msvc
rustup home:  C:\apps\rust

stable-x86_64-pc-windows-msvc (default)
rustc 1.44.1 (c7087fe00 2020-06-17)



   Compiling url v2.1.1
   Compiling chrono v0.4.11
   Compiling bincode v1.2.1
   Compiling uuid v0.8.1
   Compiling actix-router v0.2.4
   Compiling meilisearch-types v0.12.0 (C:\apps\meilisearch\MeiliSearch\meilisearch-types)
   Compiling ordered-float v1.0.2
   Compiling serde_qs v0.5.2
   Compiling structopt-derive v0.4.7
   Compiling actix-codec v0.2.0
   Compiling serde_json v1.0.53
   Compiling futures-executor v0.3.5
   Compiling actix-rt v1.1.1
   Compiling actix-service v1.0.5
   Compiling h2 v0.2.5
   Compiling serde_urlencoded v0.6.1
   Compiling ureq v0.12.1
   Compiling vergen v3.1.0
   Compiling debugid v0.7.2
   Compiling heed-types v0.7.0
   Compiling futures v0.3.5
   Compiling hyper v0.13.6
   Compiling sentry-types v0.14.1
   Compiling heed v0.8.0
   Compiling actix-utils v1.0.6
   Compiling trust-dns-proto v0.18.0-alpha.2
   Compiling hyper-rustls v0.20.0
   Compiling actix-tls v1.0.0
   Compiling actix-server v1.0.3
   Compiling trust-dns-resolver v0.18.0-alpha.2
   Compiling meilisearch-http v0.12.0 (C:\apps\meilisearch\MeiliSearch\meilisearch-http)
   Compiling reqwest v0.10.6
   Compiling actix-testing v1.0.1
   Compiling actix-connect v1.0.2
   Compiling structopt v0.3.14
   Compiling actix-http v1.0.1
   Compiling awc v1.0.1
   Compiling meilisearch-error v0.12.0 (C:\apps\meilisearch\MeiliSearch\meilisearch-error)
   Compiling actix-web v2.0.0
   Compiling meilisearch-schema v0.12.0 (C:\apps\meilisearch\MeiliSearch\meilisearch-schema)
   Compiling actix-cors v0.2.0
   Compiling meilisearch-core v0.12.0 (C:\apps\meilisearch\MeiliSearch\meilisearch-core)
    Finished release [optimized + debuginfo] target(s) in 23m 35s
     Running `target\release\meilisearch.exe`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Heed(Io(Os { code: 112, kind: Other, message: "There is not enough space on the disk." }))', meilisearch-http\src\data.rs:69:27
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Panic in Arbiter thread.
error: process didn't exit successfully: `target\release\meilisearch.exe` (exit code: 101)

c:\apps\meilisearch\MeiliSearch>cargo run --release
    Finished release [optimized + debuginfo] target(s) in 2.13s
     Running `target\release\meilisearch.exe`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Heed(Io(Os { code: 112, kind: Other, message: "**There is not enough space on the dis**k." }))', meilisearch-http\src\data.rs:69:27
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Panic in Arbiter thread.
error: process didn't exit successfully: `target\release\meilisearch.exe` (exit code: 101)

c:\apps\meilisearch\MeiliSearch>set RUST_BACKTRACE=1

c:\apps\meilisearch\MeiliSearch>cargo run --release
    Finished release [optimized + debuginfo] target(s) in 1.21s
     Running `target\release\meilisearch.exe`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Heed(Io(Os { code: 112, kind: Other, message: "There is not enough space on the disk." }))', meilisearch-http\src\data.rs:69:27
stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.46\src\backtrace\mod.rs:66
   1: std::sys_common::backtrace::_print_fmt
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\sys_common\backtrace.rs:78
   2: std::sys_common::backtrace::_print::{{impl}}::fmt
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\sys_common\backtrace.rs:59
   3: core::fmt::write
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libcore\fmt\mod.rs:1069
   4: std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\io\mod.rs:1504
   5: std::sys_common::backtrace::_print
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\sys_common\backtrace.rs:62
   6: std::sys_common::backtrace::print
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\sys_common\backtrace.rs:49
   7: std::panicking::default_hook::{{closure}}
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\panicking.rs:198
   8: std::panicking::default_hook
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\panicking.rs:218
   9: std::panicking::rust_panic_with_hook
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\panicking.rs:511
  10: std::panicking::begin_panic_handler
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\panicking.rs:419
  11: core::panicking::panic_fmt
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libcore\panicking.rs:111
  12: core::option::expect_none_failed
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libcore\option.rs:1268
  13: core::result::Result<meilisearch_core::database::Database, meilisearch_core::error::Error>::unwrap
             at C:\apps\rust\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libcore\result.rs:1005
  14: meilisearch_http::data::Data::new
             at .\meilisearch-http\src\data.rs:69
  15: meilisearch::main::{{closure}}
             at .\meilisearch-http\src\main.rs:54
  16: core::future::from_generator::{{impl}}::poll<generator-0>
             at C:\apps\rust\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libcore\future\mod.rs:66
  17: tokio::task::local::{{impl}}::poll::{{closure}}::{{closure}}
             at C:\apps\rust_cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.21\src\task\local.rs:526
  18: tokio::coop::with_budget::{{closure}}
             at C:\apps\rust_cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.21\src\coop.rs:127
  19: std::thread::local::LocalKey<core::cell::Cell<tokio::coop::Budget>>::try_with
             at C:\apps\rust\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\thread\local.rs:263
  20: std::thread::local::LocalKey<core::cell::Cell<tokio::coop::Budget>>::with
             at C:\apps\rust\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\thread\local.rs:239
  21: tokio::coop::with_budget
             at C:\apps\rust_cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.21\src\coop.rs:120
  22: tokio::coop::budget
             at C:\apps\rust_cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.21\src\coop.rs:96
  23: tokio::task::local::{{impl}}::poll::{{closure}}
             at C:\apps\rust_cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.21\src\task\local.rs:526
  24: tokio::macros::scoped_tls::ScopedKey<tokio::task::local::Context>::set<tokio::task::local::Context,closure-0,core::task::poll::Poll<core::result::Result<(), main_error::MainError>>>
             at C:\apps\rust_cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.21\src\macros\scoped_tls.rs:63
  25: tokio::task::local::LocalSet::with
             at C:\apps\rust_cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.21\src\task\local.rs:440
  26: tokio::task::local::{{impl}}::poll
             at C:\apps\rust_cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.21\src\task\local.rs:516
  27: tokio::task::local::{{impl}}::run_until::{{closure}}
             at C:\apps\rust_cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.21\src\task\local.rs:390
  28: core::future::from_generator::{{impl}}::poll<generator-0>
             at C:\apps\rust\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libcore\future\mod.rs:66
  29: tokio::runtime::basic_scheduler::enter::{{closure}}
             at C:\apps\rust_cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.21\src\runtime\basic_scheduler.rs:213
  30: tokio::macros::scoped_tls::ScopedKey<tokio::runtime::basic_scheduler::Context>::set<tokio::runtime::basic_scheduler::Context,closure-0,core::result::Result<(), main_error::MainError>>
             at C:\apps\rust_cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.21\src\macros\scoped_tls.rs:63
  31: tokio::runtime::basic_scheduler::enter
             at C:\apps\rust_cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.21\src\runtime\basic_scheduler.rs:213
  32: tokio::runtime::basic_scheduler::BasicScheduler<tokio::park::either::Either<tokio::time::driver::Driver<tokio::park::either::Either<tokio::io::driver::Driver, tokio::park::thread::ParkThread>>, tokio::park::either::Either<tokio::io::driver::Driver, tokio:
             at C:\apps\rust_cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.21\src\runtime\basic_scheduler.rs:123
  33: tokio::runtime::{{impl}}::block_on::{{closure}}
             at C:\apps\rust_cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.21\src\runtime\mod.rs:444
  34: tokio::runtime::context::enter<closure-0,core::result::Result<(), main_error::MainError>>
             at C:\apps\rust_cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.21\src\runtime\context.rs:72
  35: tokio::runtime::handle::Handle::enter<closure-0,core::result::Result<(), main_error::MainError>>
             at C:\apps\rust_cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.21\src\runtime\handle.rs:76
  36: tokio::runtime::Runtime::block_on
             at C:\apps\rust_cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.21\src\runtime\mod.rs:441
  37: tokio::task::local::LocalSet::block_on
             at C:\apps\rust_cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.21\src\task\local.rs:351
  38: actix_rt::runtime::Runtime::block_on
             at C:\apps\rust_cargo\registry\src\github.com-1ecc6299db9ec823\actix-rt-1.1.1\src\runtime.rs:89
  39: actix_rt::builder::SystemRunner::block_on
             at C:\apps\rust_cargo\registry\src\github.com-1ecc6299db9ec823\actix-rt-1.1.1\src\builder.rs:187
  40: meilisearch::main
             at .\meilisearch-http\src\main.rs:16
  41: std::rt::lang_start::{{closure}}<core::result::Result<(), main_error::MainError>>
             at C:\apps\rust\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\rt.rs:67
  42: std::rt::lang_start_internal::{{closure}}
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\rt.rs:52
  43: std::panicking::try::do_call
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\panicking.rs:331
  44: std::panicking::try
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\panicking.rs:274
  45: std::panic::catch_unwind
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\panic.rs:394
  46: std::rt::lang_start_internal
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\rt.rs:51
  47: main
  48: invoke_main
             at d:\agent\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  49: __scrt_common_main_seh
             at d:\agent\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  50: BaseThreadInitThunk
  51: RtlUserThreadStart
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Panic in Arbiter thread.
error: process didn't exit successfully: `target\release\meilisearch.exe` (exit code: 101)

c:\apps\meilisearch\MeiliSearch>
```

**Comment by MarinPostma** [comment]
Hella @anborg,
By default meilisearch preallocate 200gb memory space. This is an issue with windows that eagerly allocate this memory, and we have no solution but letting you choose how much memory you want to preallocate: https://docs.meilisearch.com/guides/advanced_guides/configuration.html#options

**Comment by anborg** [comment]
Hi Martin,  Thanks for the info. Someone in stack said the same thing.
 
https://stackoverflow.com/questions/62851161/rust-compilation-on-windows-referring-to-nonexistent-d-drive/62855845#62855845

here is an example that worked for me.

start.bat

```bat
set MEILI_DB_PATH=data.ms
set MEILI_MAIN_MAP_SIZE=409600000
set MEILI_UPDATE_MAP_SIZE=40960000
target\release\meilisearch.exe
```
Please note:
1. MEILI_MAIN_MAP_SIZE - this is the right one, but documentation has wrong env variable
2. MEILI_UPDATE_MAP_SIZE - same, doc need to be updated. 
3. Would be good if we use human redable units:  e.g 5gb 0.5gb 0.1gb etc. system can internally compute the page size etc.

I can create a pull request with documentation corrections & adding this start.bat. Let me know.

**Comment by MarinPostma** [comment]
Hey @anborg,

Happy that you could make it work! A PR for the doc would be appreciated indeed!

As for the bat script, I would prefer a special section in the readme, explaining how to overcome this issue in windows. Is this ok with you?

Thanks for your help! Cheers

**Comment by bidoubiwa** [comment]
@MarinPostma Did we change back the naming of these options? 
- `--max-udb-size`
- `--max-mdb-size`
Wasn't that the names we chose after discussion? Maybe it changed and i'm unaware.

**Comment by PolywickStudio** [comment]
Tip: if you install on WSL (Windows Linux Subsystem), you can compile on Rust/Linux, and it works without the 200GB requirement.

**Comment by Flakebi** [comment]
For those stumbling over this issue on Windows (or #471 or #643), this can be fixed by upgrading lmdb.
In the lmdb upstream repository, lazily reserving space on Windows has been implemented [in 2015](https://bugs.openldap.org/show_bug.cgi?id=8324), however it did not make its way into the `lmdb-rkv-sys` crate, which lives in [mozilla/lmdb-rs](https://github.com/mozilla/lmdb-rs).

To get this fix and make MeiliSearch usable on Windows, one has to

1. Fork https://github.com/mozilla/lmdb-rs
1. Update the submodule in lmdb-sys/lmdb to the current state of https://github.com/LMDB/lmdb
1. Also update the `.gitmodules` file to point to the new upstream, otherwise cargo will complain later that objects from the submodule cannot be found
1. Use in `Cargo.toml` and have fun

```toml
[patch.crates-io]
# Use master branch to fix reserving 200G disk space on windows
lmdb-rkv-sys = { git = "https://github.com/Flakebi/lmdb-rs" }
```

Feel free to use my fork at https://github.com/Flakebi/lmdb-rs.

**Comment by sergeevabc** [comment]
Windows 7.

``` console
$ meilisearch-windows-amd64.exe
Error: heed error; There is not enough space on the disk. (os error 112)
```

**Comment by curquiza** [comment]
Hello @sergeevabc, you need to reduce the size of the DB which is 100GiB by default:
- docs about database size: https://docs.meilisearch.com/reference/features/known_limitations.html#database-size
- docs about flags you need to pass to reduce the default DB size: https://docs.meilisearch.com/reference/features/configuration.html#max-mdb-size

This issue is due to the `lmdb-rs` dependency we use -> this package uses an old version of LMDB that does not handle the dynamic file growth for Windows. We suggested a PR some days ago to update this version and are still waiting for the answer of the maintainers: https://github.com/mozilla/lmdb-rs/pull/91

For the moment, you need to apply the workaround (with the `--max-mdb-size` flag) I suggest.

**Comment by curquiza** [comment]
Fixed by https://github.com/meilisearch/MeiliSearch/pull/1438
