### ISSUE TITLE
actix-rt:worker panics leading to very high memory usage

### ISSUE THREAD

**Issue by jatinshah** [meilisearch/MeiliSearch#912]
**Describe the bug**

Running meilisearch in production for read-only searches (GET requests). Periodically, actix-rt worker panics and over time it leads to very high memory usage. It requires re-starting meilisearch to free up the memory.

**Backtrace**
```
thread 'actix-rt:worker:3' panicked at 'called `Option::unwrap()` on a `None` value', meilisearch-core/src/bucket_sort.rs:386:24
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1069
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1504
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:515
  11: rust_begin_unwind
             at src/libstd/panicking.rs:419
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:111
  13: core::panicking::panic
             at src/libcore/panicking.rs:54
  14: core::option::Option<T>::unwrap
             at ./rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libcore/macros/mod.rs:34
  15: meilisearch_core::bucket_sort::bucket_sort_with_distinct
             at meilisearch-core/src/bucket_sort.rs:386
  16: meilisearch_core::bucket_sort::bucket_sort
             at meilisearch-core/src/bucket_sort.rs:60
  17: meilisearch_core::query_builder::QueryBuilder::query
             at meilisearch-core/src/query_builder.rs:162
  18: meilisearch_http::helpers::meilisearch::SearchBuilder::search
             at meilisearch-http/src/helpers/meilisearch.rs:161
  19: <meilisearch_http::routes::search::search_with_url_query as actix_web::service::HttpServiceFactory>::register::search_with_url_query::{{closure}}
             at meilisearch-http/src/routes/search.rs:160
  20: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libcore/future/mod.rs:66
  21: <actix_web::handler::HandlerServiceResponse<T,R> as core::future::future::Future>::poll
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-2.0.0/src/handler.rs:138
  22: <actix_web::handler::ExtractResponse<T,S> as core::future::future::Future>::poll
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-2.0.0/src/handler.rs:247
  23: <actix_web::handler::ExtractResponse<T,S> as core::future::future::Future>::poll
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-2.0.0/src/handler.rs:258
  24: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.5/src/future/future/map.rs:67
  25: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.5/src/lib.rs:107
  26: <core::pin::Pin<P> as core::future::future::Future>::poll
             at ./rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libcore/future/future.rs:118
  27: <core::pin::Pin<P> as core::future::future::Future>::poll
             at ./rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libcore/future/future.rs:118
  28: <futures_util::future::either::Either<A,B> as core::future::future::Future>::poll
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.5/src/future/either.rs:66
  29: <core::pin::Pin<P> as core::future::future::Future>::poll
             at ./rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libcore/future/future.rs:118
  30: <core::pin::Pin<P> as core::future::future::Future>::poll
             at ./rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libcore/future/future.rs:118
  31: <actix_cors::CorsMiddleware<S> as actix_service::Service>::call::{{closure}}
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-cors-0.2.0/src/lib.rs:773
  32: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libcore/future/mod.rs:66
  33: <core::pin::Pin<P> as core::future::future::Future>::poll
             at ./rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libcore/future/future.rs:118
  34: <futures_util::future::either::Either<A,B> as core::future::future::Future>::poll
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.5/src/future/either.rs:66
  35: <actix_web::middleware::logger::LoggerResponse<S,B> as core::future::future::Future>::poll
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-2.0.0/src/middleware/logger.rs:210
  36: <actix_web::middleware::compress::CompressResponse<S,B> as core::future::future::Future>::poll
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-2.0.0/src/middleware/compress.rs:136
  37: actix_http::h1::dispatcher::InnerDispatcher<T,S,B,X,U>::handle_request
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-http-1.0.1/src/h1/dispatcher.rs:486
  38: actix_http::h1::dispatcher::InnerDispatcher<T,S,B,X,U>::poll_request
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-http-1.0.1/src/h1/dispatcher.rs:541
  39: <actix_http::h1::dispatcher::Dispatcher<T,S,B,X,U> as core::future::future::Future>::poll
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-http-1.0.1/src/h1/dispatcher.rs:744
  40: <actix_http::service::HttpServiceHandlerResponse<T,S,B,X,U> as core::future::future::Future>::poll
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-http-1.0.1/src/service.rs:637
  41: <actix_service::and_then::AndThenServiceResponse<A,B> as core::future::future::Future>::poll
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-service-1.0.5/src/and_then.rs:103
  42: <actix_server::service::StreamService<T> as actix_service::Service>::call::{{closure}}
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-server-1.0.3/src/service.rs:85
  43: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libcore/future/mod.rs:66
  44: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/task/core.rs:173
  45: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/loom/std/unsafe_cell.rs:14
  46: tokio::runtime::task::core::Core<T,S>::poll
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/task/core.rs:158
  47: tokio::runtime::task::harness::Harness<T,S>::poll::{{closure}}
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/task/harness.rs:107
  48: core::ops::function::FnOnce::call_once
             at ./rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libcore/ops/function.rs:232
  49: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at ./rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libstd/panic.rs:318
  50: std::panicking::try::do_call
             at ./rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libstd/panicking.rs:331
  51: std::panicking::try
             at ./rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libstd/panicking.rs:274
  52: std::panic::catch_unwind
             at ./rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libstd/panic.rs:394
  53: tokio::runtime::task::harness::Harness<T,S>::poll
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/task/harness.rs:89
  54: tokio::runtime::task::raw::poll
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/task/raw.rs:104
  55: tokio::runtime::task::raw::RawTask::poll
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/task/raw.rs:66
  56: tokio::runtime::task::Notified<S>::run
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/task/mod.rs:169
  57: tokio::task::local::LocalSet::tick::{{closure}}
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/task/local.rs:406
  58: tokio::coop::with_budget::{{closure}}
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/coop.rs:127
  59: std::thread::local::LocalKey<T>::try_with
             at ./rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libstd/thread/local.rs:263
  60: std::thread::local::LocalKey<T>::with
             at ./rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libstd/thread/local.rs:239
  61: tokio::coop::with_budget
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/coop.rs:120
  62: tokio::coop::budget
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/coop.rs:96
  63: tokio::task::local::LocalSet::tick
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/task/local.rs:406
  64: <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll::{{closure}}
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/task/local.rs:530
  65: tokio::macros::scoped_tls::ScopedKey<T>::set
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/macros/scoped_tls.rs:63
  66: tokio::task::local::LocalSet::with
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/task/local.rs:440
  67: <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/task/local.rs:516
  68: tokio::task::local::LocalSet::run_until::{{closure}}
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/task/local.rs:390
  69: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libcore/future/mod.rs:66
  70: tokio::runtime::enter::Enter::block_on::{{closure}}
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/enter.rs:163
  71: tokio::coop::with_budget::{{closure}}
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/coop.rs:127
  72: std::thread::local::LocalKey<T>::try_with
             at ./rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libstd/thread/local.rs:263
  73: std::thread::local::LocalKey<T>::with
             at ./rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libstd/thread/local.rs:239
  74: tokio::coop::with_budget
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/coop.rs:120
  75: tokio::coop::budget
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/coop.rs:96
  76: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on::{{closure}}
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/basic_scheduler.rs:131
  77: tokio::runtime::basic_scheduler::enter::{{closure}}
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/basic_scheduler.rs:213
  78: tokio::macros::scoped_tls::ScopedKey<T>::set
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/macros/scoped_tls.rs:63
  79: tokio::runtime::basic_scheduler::enter
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/basic_scheduler.rs:213
  80: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/basic_scheduler.rs:123
  81: tokio::runtime::Runtime::block_on::{{closure}}
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/mod.rs:444
  82: tokio::runtime::context::enter
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/context.rs:72
  83: tokio::runtime::handle::Handle::enter
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/handle.rs:76
  84: tokio::runtime::Runtime::block_on
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/mod.rs:441
  85: tokio::task::local::LocalSet::block_on
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/task/local.rs:351
  86: actix_rt::runtime::Runtime::block_on
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-rt-1.1.1/src/runtime.rs:89
  87: actix_rt::arbiter::Arbiter::new::{{closure}}
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-rt-1.1.1/src/arbiter.rs:137
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by jatinshah** [comment]
Similar problem discussed on actix repo: https://github.com/actix/actix-web/issues/763

**Comment by MarinPostma** [comment]
@jatinshah thanks for reporting

@Kerollmops any idea how this happens? Let's error instead of panicking here, until we find what's wrong. Working on a pr.

**Comment by jatinshah** [comment]
Thanks! It's quite an important issue for production deployment.

Currently, I have to run a script in background to monitor CPU/Memory usage and restart the Meilisearch server if CPU usage crosses a threshold. If I don't do that, then over time CPU usage goes to 100% and Meilisearch server stops working.
